winobj_assocwindow ::= 'assocWindow(' handle ')'

winobj_handle ::= 'handle'

winobj_title ::= 'title'

winobj_title_equal ::= 'title' '=' newtitle

winobj_wclass ::= 'wclass'

winobj_id ::= 'id'

winobj_coordinates ::= 'coordinates'

winobj_state ::= 'state'

winobj_getstyle ::= 'getStyle'

winobj_restore ::= 'restore'

winobj_hide ::= 'hide'

winobj_minimize ::= 'minimize'

winobj_maximize ::= 'maximize'

winobj_resize ::= 'resize(' width ',' height ')'

winobj_enable ::= 'enable'

winobj_disable ::= 'disable'

winobj_moveto ::= 'moveTo(' x ',' y ')'

winobj_toforeground ::= 'toForeground'

winobj_focusnextitem ::= 'focusNextItem'

winobj_focuspreviousitem ::= 'focusPreviousItem'

winobj_focusitem ::= 'focusItem(' wndObject ')'

winobj_findchild ::= 'findChild(' label ')'

winobj_childatposition ::= 'childAtPosition(' x ',' y ')'

winobj_next ::= 'next'

winobj_previous ::= 'previous'

winobj_first ::= 'first'

winobj_last ::= 'last'

winobj_owner ::= 'owner'

winobj_firstchild ::= 'firstChild'

winobj_enumeratechildren ::= 'enumerateChildren'

winobj_sendmessage ::= 'sendMessage(' message ',' wParam ',' lParam ')'

winobj_sendcommand ::= 'sendCommand(' command ')'

winobj_sendmenucommand ::= 'sendMenuCommand(' id ')'

winobj_sendmouseclick ::= 'sendMouseClick(' ( 'RIGHT' | 'LEFT' | 'MIDDLE' ) ','
                                                    ( 'UP' | 'DOWN' | 'DBLCLK' ) ','
                                                    x ',' y ( ','
                                                    ( 'LEFTDOWN' | 'RIGHTDOWN' |
                                                      'MIDDLEDOWN' | 'SHIFT' |
                                                      'CONTROL' ) )+ ')'

winobj_sendsyscommand ::= 'sendSysCommand(' ( 'SIZE' | 'MOVE' | 'MINIMIZE' | 'MAXIMIZE' |
                                                      'NEXTWINDOW' | 'PREVWINDOW' | 'CLOSE' |
                                                      'VSCROLL' | 'HSCROLL' | 'ARRANGE' | 'RESTORE' |
                                                      'TASKLIST' | 'SCREENSAVE' | 'CONTEXTHELP' ) ')'

winobj_pushbutton ::= 'pushButton(' label ')'

winobj_sendkey ::= 'sendKey(' keyName ( ',' ( alt )? ( ',' ext )? )? ')'

winobj_sendchar ::= 'sendChar(' character ( ',' alt )? ')'

winobj_sendkeydown ::= 'sendKeyDown(' keyName ( ',' ext )? ')'

winobj_sendkeyup ::= 'sendKeyUp(' keyName ( ',' ext )? ')'

winobj_sendtext ::= 'sendText(' text ')'

winobj_menu ::= 'menu'

winobj_systemmenu ::= 'systemMenu'

winobj_ismenu ::= 'isMenu'

winobj_processmenucommand ::= 'processMenuCommand(' ( menu )? ( ',' submenu )+ ',' menuitem ')'

