// Ported from Rust to C++ by Claude Sonnet 5.

// Copyright 2012-2026 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// http://rust-lang.org/COPYRIGHT.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

#pragma once
//------------------------------------------------------------------------------
// Hand-written file (NOT autogenerated) - mirrors src/lookup.rs. Rust's
// `const IS_CJK: bool` generic becomes a C++ `template <bool IS_CJK>`
// non-type template parameter. Both instantiations (true/false) are
// explicitly instantiated in lookup.cpp.
//
// Targets C++11: no std::optional (C++17), no `if constexpr` (C++17) in the
// implementation.
//------------------------------------------------------------------------------

#include <cstdint>
#include <utility>
#include <vector>

#include "width_info.hpp"

namespace unicode_width {

// Port of width_in_generic<IS_CJK>(): returns the width contribution of `c`
// and the new WidthInfo state, given the state built up from codepoints to
// its right (see str_width()'s right-to-left scan below).
template <bool IS_CJK>
std::pair<std::int8_t, WidthInfo> width_in_generic(char32_t c, WidthInfo next_info);

#if 0
// Port of str_width()/str_width_cjk(): total display width of a codepoint
// sequence. Scans RIGHT TO LEFT, mirroring the Rust implementation's use of
// Iterator::rfold - width_in_generic needs the state built up from
// characters to the right of the one currently being processed.
template <bool IS_CJK>
std::int64_t str_width(const std::vector<char32_t> &codepoints);
#endif

#if 0
// Convenience: decode a UTF-8 buffer (via utf8proc) and compute str_width().
// Throws std::runtime_error on invalid UTF-8.
template <bool IS_CJK>
std::int64_t utf8_str_width(const std::uint8_t *data, std::size_t length);
#endif

extern template std::pair<std::int8_t, WidthInfo> width_in_generic<false>(char32_t, WidthInfo);
extern template std::pair<std::int8_t, WidthInfo> width_in_generic<true>(char32_t, WidthInfo);
#if 0
extern template std::int64_t str_width<false>(const std::vector<char32_t> &);
extern template std::int64_t str_width<true>(const std::vector<char32_t> &);
extern template std::int64_t utf8_str_width<false>(const std::uint8_t *, std::size_t);
extern template std::int64_t utf8_str_width<true>(const std::uint8_t *, std::size_t);
#endif

// For information
void sizeofUnicodeWidthTables();

} // namespace unicode_width
