// Ported from Rust to C++ by Claude Sonnet 5.

// Copyright 2012-2026 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// http://rust-lang.org/COPYRIGHT.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

#pragma once
//------------------------------------------------------------------------------
// Hand-written file (NOT autogenerated). Declares the property predicates
// whose bodies are generated into gen/props.cpp by scripts/unicode-cpp.py,
// plus is_transparent_zero_width()/is_solidus_transparent() (hand-written
// in the Rust crate too - ported here 1:1 from src/props.rs) and the small
// RangePair binary-search helper the generated leaf tables use.
//------------------------------------------------------------------------------

#include <cstdint>
#include <cstddef>

namespace unicode_width {

// A closed [lo, hi] byte range, used by the generated two-level leaf tables
// (TEXT_PRESENTATION_LEAF_*, EMOJI_MODIFIER_LEAF_*). Mirrors Rust's `(u8, u8)`.
struct RangePair {
    std::uint8_t lo;
    std::uint8_t hi;
};

// Binary search over a sorted, non-overlapping RangePair array. Mirrors the
// `binary_search_by` closures scripts/unicode.py emits into props.rs.
bool range_pair_contains(const RangePair *ranges, std::size_t len, std::uint8_t v);

// -- Generated (gen/props.cpp) --

// Whether this character has Joining_Group=Lam.
bool is_joining_group_lam(char32_t c);

// Whether this character is a default-ignorable combining mark or ZWJ.
// These characters won't interrupt non-Arabic ligatures.
bool is_ligature_transparent(char32_t c);

// Whether this character forms an emoji presentation sequence
// (https://www.unicode.org/reports/tr51/#def_emoji_presentation_sequence)
// when followed by U+FE0F. Emoji presentation sequences have width 2.
bool starts_emoji_presentation_seq(char32_t c);

// Returns true if `c` has default emoji presentation, but forms a text
// presentation sequence
// (https://www.unicode.org/reports/tr51/#def_text_presentation_sequence)
// when followed by U+FE0E, and is not ideographic. Such sequences have
// width 1.
bool starts_non_ideographic_text_presentation_seq(char32_t c);

// Returns true if `c` is an Emoji_Modifier_Base.
bool is_emoji_modifier_base(char32_t c);

// -- Hand-written (this behavior is hand-written in Rust too, in src/props.rs) --

// Whether this character is a zero-width character with
// Joining_Type=Transparent. Used by the Alef-Lamed ligatures. See also
// is_ligature_transparent(), a near-subset of this (only ZWJ is excepted)
// which is transparent for non-Arabic ligatures.
bool is_transparent_zero_width(char32_t c);

// Whether this character is transparent wrt the effect of U+0338 COMBINING
// LONG SOLIDUS OVERLAY on its base character. (CJK-only, matching the
// Rust crate's `#[cfg(feature = "cjk")]` gate on this function.)
bool is_solidus_transparent(char32_t c);

} // namespace unicode_width
