// Ported from Rust to C++ by Claude Sonnet 5.

// Copyright 2012-2026 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// http://rust-lang.org/COPYRIGHT.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

#pragma once
//------------------------------------------------------------------------------
// Hand-written file (NOT autogenerated). Constants are defined in
// gen/width_info.cpp, which IS generated by scripts/unicode-cpp.py.
//
// Targets C++11 (no digit separators, no constexpr - nothing here needs to
// be compile-time evaluable, so plain inline member functions with
// ordinary if/else are simpler and avoid C++11's "single return statement"
// restriction on constexpr functions).
//------------------------------------------------------------------------------

#include <cstdint>

namespace unicode_width {

class WidthInfo {
public:
    WidthInfo() : bits_(0) {}
    explicit WidthInfo(std::uint16_t bits) : bits_(bits) {}

    bool operator==(const WidthInfo &o) const { return bits_ == o.bits_; }
    bool operator!=(const WidthInfo &o) const { return bits_ != o.bits_; }

    std::uint16_t raw() const { return bits_; }

    bool is_ligature_transparent() const {
        return (bits_ & 0x0800) == 0x0800;
    }

    WidthInfo set_zwj_bit() const {
        return WidthInfo(bits_ | 0x0400);
    }

    bool is_emoji_presentation() const {
        return (bits_ & VARIATION_SELECTOR_16.bits_) == VARIATION_SELECTOR_16.bits_;
    }

    bool is_zwj_emoji_presentation() const {
        return (bits_ & 0xB000) == 0x9000;
    }

    WidthInfo set_emoji_presentation() const {
        if ((bits_ & LIGATURE_TRANSPARENT_MASK) == LIGATURE_TRANSPARENT_MASK ||
            (bits_ & 0x9000) == 0x1000) {
            return WidthInfo(bits_ |
                (VARIATION_SELECTOR_16.bits_ & ~VARIATION_SELECTOR_15.bits_ &
                 ~VARIATION_SELECTOR_1_2_OR_3.bits_));
        }
        return VARIATION_SELECTOR_16;
    }

    WidthInfo unset_emoji_presentation() const {
        if ((bits_ & LIGATURE_TRANSPARENT_MASK) == LIGATURE_TRANSPARENT_MASK) {
            return WidthInfo(bits_ & ~VARIATION_SELECTOR_16.bits_);
        }
        return DEFAULT;
    }

    bool is_text_presentation() const {
        return (bits_ & VARIATION_SELECTOR_15.bits_) == VARIATION_SELECTOR_15.bits_;
    }

    WidthInfo set_text_presentation() const {
        if ((bits_ & LIGATURE_TRANSPARENT_MASK) == LIGATURE_TRANSPARENT_MASK) {
            return WidthInfo(bits_ |
                (VARIATION_SELECTOR_15.bits_ & ~VARIATION_SELECTOR_16.bits_ &
                 ~VARIATION_SELECTOR_1_2_OR_3.bits_));
        }
        return WidthInfo(VARIATION_SELECTOR_15.bits_);
    }

    WidthInfo unset_text_presentation() const {
        return WidthInfo(bits_ & ~VARIATION_SELECTOR_15.bits_);
    }

    bool is_vs1_2_3() const {
        return (bits_ & VARIATION_SELECTOR_1_2_OR_3.bits_) == VARIATION_SELECTOR_1_2_OR_3.bits_;
    }

    WidthInfo set_vs1_2_3() const {
        if ((bits_ & LIGATURE_TRANSPARENT_MASK) == LIGATURE_TRANSPARENT_MASK) {
            return WidthInfo(bits_ |
                (VARIATION_SELECTOR_1_2_OR_3.bits_ & ~VARIATION_SELECTOR_15.bits_ &
                 ~VARIATION_SELECTOR_16.bits_));
        }
        return WidthInfo(VARIATION_SELECTOR_1_2_OR_3.bits_);
    }

    WidthInfo unset_vs1_2_3() const {
        return WidthInfo(bits_ & ~VARIATION_SELECTOR_1_2_OR_3.bits_);
    }

    // ---- Constants (defined in gen/width_info.cpp) ----
    static const WidthInfo DEFAULT;
    static const WidthInfo LINE_FEED;
    static const WidthInfo EMOJI_MODIFIER;
    static const WidthInfo REGIONAL_INDICATOR;
    static const WidthInfo SEVERAL_REGIONAL_INDICATOR;
    static const WidthInfo EMOJI_PRESENTATION;
    static const WidthInfo ZWJ_EMOJI_PRESENTATION;
    static const WidthInfo VS16_ZWJ_EMOJI_PRESENTATION;
    static const WidthInfo KEYCAP_ZWJ_EMOJI_PRESENTATION;
    static const WidthInfo VS16_KEYCAP_ZWJ_EMOJI_PRESENTATION;
    static const WidthInfo REGIONAL_INDICATOR_ZWJ_PRESENTATION;
    static const WidthInfo EVEN_REGIONAL_INDICATOR_ZWJ_PRESENTATION;
    static const WidthInfo ODD_REGIONAL_INDICATOR_ZWJ_PRESENTATION;
    static const WidthInfo TAG_END_ZWJ_EMOJI_PRESENTATION;
    static const WidthInfo TAG_D1_END_ZWJ_EMOJI_PRESENTATION;
    static const WidthInfo TAG_D2_END_ZWJ_EMOJI_PRESENTATION;
    static const WidthInfo TAG_D3_END_ZWJ_EMOJI_PRESENTATION;
    static const WidthInfo TAG_A1_END_ZWJ_EMOJI_PRESENTATION;
    static const WidthInfo TAG_A2_END_ZWJ_EMOJI_PRESENTATION;
    static const WidthInfo TAG_A3_END_ZWJ_EMOJI_PRESENTATION;
    static const WidthInfo TAG_A4_END_ZWJ_EMOJI_PRESENTATION;
    static const WidthInfo TAG_A5_END_ZWJ_EMOJI_PRESENTATION;
    static const WidthInfo TAG_A6_END_ZWJ_EMOJI_PRESENTATION;
    static const WidthInfo KIRAT_RAI_VOWEL_SIGN_E;
    static const WidthInfo KIRAT_RAI_VOWEL_SIGN_AI;
    static const WidthInfo VARIATION_SELECTOR_1_2_OR_3;
    static const WidthInfo VARIATION_SELECTOR_15;
    static const WidthInfo VARIATION_SELECTOR_16;
    static const WidthInfo JOINING_GROUP_ALEF;
    static const WidthInfo COMBINING_LONG_SOLIDUS_OVERLAY;
    static const WidthInfo SOLIDUS_OVERLAY_ALEF;
    static const WidthInfo HEBREW_LETTER_LAMED;
    static const WidthInfo ZWJ_HEBREW_LETTER_LAMED;
    static const WidthInfo BUGINESE_LETTER_YA;
    static const WidthInfo ZWJ_BUGINESE_LETTER_YA;
    static const WidthInfo BUGINESE_VOWEL_SIGN_I_ZWJ_LETTER_YA;
    static const WidthInfo TIFINAGH_CONSONANT;
    static const WidthInfo ZWJ_TIFINAGH_CONSONANT;
    static const WidthInfo TIFINAGH_JOINER_CONSONANT;
    static const WidthInfo LISU_TONE_LETTER_MYA_NA_JEU;
    static const WidthInfo OLD_TURKIC_LETTER_ORKHON_I;
    static const WidthInfo ZWJ_OLD_TURKIC_LETTER_ORKHON_I;
    static const WidthInfo KHMER_COENG_ELIGIBLE_LETTER;

private:
    std::uint16_t bits_;
    static const std::uint16_t LIGATURE_TRANSPARENT_MASK = 0x2000;
};

} // namespace unicode_width
