#/*----------------------------------------------------------------------------*/
#/*                                                                            */
#/* Copyright (c) 2012-2013 Rexx Language Association. All rights reserved.    */
#/*                                                                            */
#/* This program and the accompanying materials are made available under       */
#/* the terms of the Common Public License v1.0 which accompanies this         */
#/* distribution. A copy is also available at the following address:           */
#/* http://www.oorexx.org/license.html                                         */
#/*                                                                            */
#/* Redistribution and use in source and binary forms, with or                 */
#/* without modification, are permitted provided that the following            */
#/* conditions are met:                                                        */
#/*                                                                            */
#/* Redistributions of source code must retain the above copyright             */
#/* notice, this list of conditions and the following disclaimer.              */
#/* Redistributions in binary form must reproduce the above copyright          */
#/* notice, this list of conditions and the following disclaimer in            */
#/* the documentation and/or other materials provided with the distribution.   */
#/*                                                                            */
#/* Neither the name of Rexx Language Association nor the names                */
#/* of its contributors may be used to endorse or promote products             */
#/* derived from this software without specific prior written permission.      */
#/*                                                                            */
#/* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS        */
#/* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT          */
#/* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS          */
#/* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT   */
#/* OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,      */
#/* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED   */
#/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,        */
#/* OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY     */
#/* OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING    */
#/* NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS         */
#/* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.               */
#/*                                                                            */
#/*----------------------------------------------------------------------------*/

# This is a nMake compatible make file to create the resource-only DLL for the
# EditControlEx.rex example.  It is intended to be used as part of the packaging
# system for the Extra ooDialog Examples package.  It expects that the MACHINE
# environment variable has been set.  The packaging system does this normally.
#
# If you have nMake, rc, and link, and wish to use this make file to re-compile
# the resource-only DLL, you can define MACHINE on the command line, use this
# syntax to build the DLL:
#
#   nMake /NOLOGO MACHINE=X64
#
# The /NOLOGO flag is optional and the value for MACHINE= should be X64 to build
# a 64-bit DLL and X86 to build a 32-bit DLL.
#
# If needed, it may be easier to use the makeDLL.rex program distributed with
# the Extra ooDialog Examples package to rebuild the EditControlEx.dll file from
# source.  makeDll.rex is accompanied by a read me file explaining how to use
# it.

BASE_NAME = EditControlEx

$(BASE_NAME).dll : $(BASE_NAME).res
  link $(BASE_NAME).res /NOENTRY /DLL /MACHINE:$(MACHINE) /OUT:$(BASE_NAME).dll

$(BASE_NAME).res : $(BASE_NAME).rc $(BASE_NAME).h
  rc /DWIN32 /R /FO$(BASE_NAME).res $(BASE_NAME).rc
