csvstream_close ::= close

csvstream_csvlinein ::= csvlinein

csvstream_scvlineout ::= 'csvlineout(' collection_object ')'

csvstream_getheaders ::= getheaders

csvstream_init ::= 'init(' name ( HeadersExist )? ')'

csvstream_setheaders ::= 'setheaders(' headerobj ')'

