hostemu_execio ::= ( num | '*' ) ( 'DISKR' | 'DISKW' ) filename '(' 
                   ( 'FINIS' 'STEM' stemname | 'STEM' stemname 'FINIS' | 'STEM' stemname |
                     'FINIS' ( 'LIFO' | 'FIFO' | 'SKIP' ) )?

hostemu_hi ::= 'HI'

hostemu_te ::= 'TE'

hostemu_ts ::= 'TS'

