
json_fromjson ::= 'fromJSON(' string ')'

json_fromjson_file ::= 'fromJSONFile('  fileName ')'

json_tojson ::= 'toJSON(' rexxObject (',' legible )? ')'

json_tojson_file ::= 'toJSONFile(' fileName ',' rexxObject (',' legible )? ')'

json_legible_arg ::= ( '.false' <?rr u?> | '.true' )?

jsonboolean_true ::= 'true'

jsonboolean_false ::= 'false'

json_true ::= 'true'

json_false ::= 'false'

json_init ::= 'init'

