alarm_attachment ::= 'attachment'

alarm_cancel ::= 'cancel'

alarm_canceled ::= 'canceled' | 'cancelled'

alarm_init ::= 'init(' atime ',' message (',' attachment)? ')'

alarm_scheduledtime ::= 'scheduledTime'

alarm_triggered ::= 'triggered'
