coll_atget ::= '[' index ( ( ',' index )+ )? ']'

coll_putset ::= '[' index ( ( ',' index )+ )? ']' '=' value

coll_allindexes ::= 'allindexes'

coll_allitems ::= 'allitems'

coll_at ::= 'at(' index ( ( ',' index )+ )? ')'

coll_difference ::= 'difference(' argument ')'

coll_disjoint ::= 'disjoint(' argument ')'

coll_equivalent ::= 'equivalent(' argument ')'

coll_hasindex ::= 'hasIndex(' index ( ( ',' index )+ )? ')'

coll_hasitem ::= 'hasItem(' item ')'

coll_index ::= 'index(' item ')'

coll_intersection ::= 'intersection(' argument ')'

coll_items ::= 'items'

coll_makearray ::= 'makearray'

coll_put ::= 'put(' item ',' ( index ( ( ',' index )+ )? ) ')'

coll_subset ::= 'subset(' argument ')'

coll_supplier ::= 'supplier'

coll_union ::= 'union(' argument ')'

coll_xor ::= 'xor(' argument ')'

map_makearray ::= 'makearray'

map_putall ::= 'putAll(' collection ')'

ordered_append ::= 'append(' item ')'

ordered_appendall ::= 'appendAll(' collection ')'

ordered_delete ::= 'delete(' index ( ( ',' index )+ )? ')'

ordered_difference ::= 'difference(' argument ')'

ordered_first ::= 'first'

ordered_firstitem ::= 'firstItem'

ordered_insert ::= 'insert(' item ( ',' index )? ')'

ordered_intersection ::= 'intersection(' argument ')'

ordered_last ::= 'last'

ordered_lastitem ::= 'lastItem'

ordered_next ::= 'next'

ordered_previous ::= 'previous(' index ')'

ordered_section ::= 'section(' start ( ',' items )? ')'

ordered_sort ::= 'sort'

ordered_sortwith ::= 'sortWith(' comparator ')'

ordered_stablesort ::= 'stableSort'

ordered_stablesortwith ::= 'stableSortWith(' comparator ')'

ordered_subset ::= 'subset(' argument ')'

ordered_union ::= 'union(' argument ')'

ordered_xor ::= 'xor(' argument ')'




















