coll_atget ::= '[' index ( ( ',' index )+ )? ']'

coll_putset ::= '[' index ( ( ',' index )+ )? ']' '=' value

coll_allindexes ::= 'allindexes'

coll_allitems ::= 'allitems'

coll_at ::= 'at(' index ( ( ',' index )+ )? ')'

coll_differences ::= 'differences(' argument ')'

coll_disjoint ::= 'disjoint(' argument ')'

coll_equivalent ::= 'equivalent(' argument ')'

coll_hasindex ::= 'hasIndex(' index ( ( ',' index )+ )? ')'

coll_hasitem ::= 'hasItem(' item ')'

coll_index ::= 'index(' item ')'

coll_intersection ::= 'intersection(' argument ')'

coll_items ::= 'items'

coll_makearray ::= 'makearray'

coll_put ::= 'put(' item ',' ( index ( ( ',' index )+ )? ) ')'

coll_subset ::= 'subset(' argument ')'

coll_supplier ::= 'supplier'

coll_union ::= 'union(' argument ')'

coll_xor ::= 'xor(' argument ')'



