coll_atget ::= '[' index ( ( ',' index )+ )? ']'

coll_putset ::= '[' index ( ( ',' index )+ )? ']' '=' value

coll_allindexes ::= 'allindexes'

coll_allitems ::= 'allitems'

coll_at ::= 'at(' index ( ( ',' index )+ )? ')'

coll_difference ::= 'difference(' argument ')'

coll_disjoint ::= 'disjoint(' argument ')'

coll_equivalent ::= 'equivalent(' argument ')'

coll_hasindex ::= 'hasIndex(' index ( ( ',' index )+ )? ')'

coll_hasitem ::= 'hasItem(' item ')'

coll_index ::= 'index(' item ')'

coll_intersection ::= 'intersection(' argument ')'

coll_items ::= 'items'

coll_makearray ::= 'makearray'

coll_put ::= 'put(' item ',' ( index ( ( ',' index )+ )? ) ')'

coll_subset ::= 'subset(' argument ')'

coll_supplier ::= 'supplier'

coll_union ::= 'union(' argument ')'

coll_xor ::= 'xor(' argument ')'

map_makearray ::= 'makearray'

map_putall ::= 'putAll(' collection ')'

ordered_append ::= 'append(' item ')'

ordered_appendall ::= 'appendAll(' collection ')'

ordered_delete ::= 'delete(' index ( ( ',' index )+ )? ')'

ordered_difference ::= 'difference(' argument ')'

ordered_first ::= 'first'

ordered_firstitem ::= 'firstItem'

ordered_insert ::= 'insert(' item ( ',' index )? ')'

ordered_intersection ::= 'intersection(' argument ')'

ordered_last ::= 'last'

ordered_lastitem ::= 'lastItem'

ordered_next ::= 'next'

ordered_previous ::= 'previous(' index ')'

ordered_section ::= 'section(' start ( ',' items )? ')'

ordered_sort ::= 'sort'

ordered_sortwith ::= 'sortWith(' comparator ')'

ordered_stablesort ::= 'stableSort'

ordered_stablesortwith ::= 'stableSortWith(' comparator ')'

ordered_subset ::= 'subset(' argument ')'

ordered_union ::= 'union(' argument ')'

ordered_xor ::= 'xor(' argument ')'

array_insert ::= 'insert(' item ( ',' index )? ')'

array_new ::= 'new' ( '(' size ( ( ',' size )+ )? ')' )?

array_of ::= 'of' ( '(' item ( ( ',' item )+ )? ')' )?

array_atget ::= '[' index ( ( ',' index )+ )? ']'

array_putset ::= '[' index ( ( ',' index )+ )? ']' '=' value

array_allindexes ::= 'allIndexes'

array_allitems ::= 'allItems'

array_append ::= 'append(' item ')'

array_at ::= 'at(' index ( ( ',' index )+ )? ')'

array_delete ::= 'delete(' index ( ( ',' index )+ )? ')'

array_dimension ::= 'dimension(' n ')'

array_dimensions ::= 'dimensions'

array_empty ::= 'empty'

array_fill ::= 'fill(' value ')'

array_first ::= 'first'

array_firstitem ::= 'firstItem'

array_hasindex ::= 'hasIndex(' index ( ( ',' index )+ )? ')'

array_hasitem ::= 'hasItem(' item ')'

array_index ::= 'index(' item ')'

array_isempty ::= 'isEmpty'

attay_items ::= 'items'

array_last ::= 'last'

array_lastitem ::= 'lastItem'

array_makearray ::= 'makeArray'

array_makestring ::= 'makeString(' ( 'Line' ( ',' seperator )? | 'Char' )? ')'

array_next ::= 'next(' index ')'

array_previous ::= 'previous(' index ')'

array_put ::= 'put(' item ( index ( ( ',' index )+ )? ) ')'

array_remove ::= 'remove(' index ( ( ',' index )+ )? ')'

array_removeitem ::= 'removeItem(' item ')'

array_section ::= 'section(' start ( ',' items )? ')'

array_size ::= 'size'

array_sort ::= 'sort'

array_sortwith ::= 'sortWith(' comparator ')'

array_stablesort ::= 'stableSort'

array_stablesortwith ::= 'stableSortWith(' comparator ')'

array_supplier ::= 'supplier'

array_tostring ::= 'toString(' ( 'Line' ( ',' separator )? | 'Char' )? ')'

bag_of ::= 'of' ( '(' item ( ( ',' item )+ )? ')' )?

bag_putset ::= '[' index ']' '=' item

bag_difference ::= 'difference(' argument ')'

bag_hasindex ::= 'hasIndex(' index ')'

bag_intersection ::= 'intersection(' argument ')'

bag_put ::= 'put(' item ',' index ')'

bag_putall ::= 'putAll(' collection ')'

bag_subset ::= 'subset(' argument ')'

bag_union ::= 'union(' argument ')'

bag_xor ::= 'xor(' argument ')'

cqueue_of ::= 'of' ( '(' item ( ( ',' item )+ )? ')' )?

cqueue_init ::= 'init(' size ')'

cqueue_append ::= 'append(' item ')'

cqueue_insert ::= 'insert(' item ( ',' index )? ')'

cqueue_intersection ::= 'intersection(' argument ')'

cqueue_makearray ::= 'makeArray(' ( order )? ')'

cqueue_push ::= 'push(' item ( ',' option )? ')'

cqueue_queue ::= 'queue(' item ( ',' 'Normal' | ',' 'Unique' )? ')'

cqueue_resize ::= 'resize(' newsize ( ',' order )? ')'

cqueue_section ::= 'section(' start ( ',' items )? ')'

cqueue_size ::= 'size'

cqueue_string ::= 'string(' ( '","' | delimiter )? ( ',' 'Fifo' | ',' order )? ')'

cqueue_supplier ::= 'supplier(' ( order )? ')'

cqueue_union ::= 'union(' argument ')'

cqueue_xor ::= 'xor(' argument ')'

directory_new ::= 'new'

directory_atget ::= '[' name ']'

directory_putset ::= '[' name ']' '=' item

directory_allindexes ::= 'allIndexes'

directory_allitems ::= 'allItems'

directory_at ::= 'at(' name ')'

directory_empty ::= 'empty'

directory_entry ::= 'entry(' name ')'

directory_hasentry ::= 'hasEntry(' name ')'

directory_hasindex ::= 'hasIndex(' name ')'

directory_hasitem ::= 'hasItem(' item ')'

directory_index ::= 'index(' item ')'

directory_isempty ::= 'isEmpty'

directory_items ::= 'items'

directory_makearray ::= 'makeArray'

directory_put ::= 'put(' item ',' name ')'

directory_remove ::= 'remove(' name ')'

directory_removeitem ::= 'removeItem(' item ')'

directory_setentry ::= 'setEntry(' name ( ',' entry )? ')'

directory_setmethod ::= 'setMethod(' name ( ',' method )? ')'

directory_supplier ::= 'supplier'

directory_unknown ::= 'unknown(' messagename ',' messageargs ')'

directory_unsetmethod ::= 'unsetMethod(' name ')'

directory_xor ::= 'xor(' argument ')'

list_new ::= 'new'

list_of ::= 'of' ( '(' item ( ( ',' item )+ )? ')' )?

list_atget ::= '[' index ']'

list_putsett ::= '[' index ']' '=' item

list_allindexes ::= 'allIndexes'

list_allitems ::= 'allItems'

list_append ::= 'append(' item ')'

list_at ::= 'at(' index ')'

list_delete ::= 'delete(' index ')'

list_empty ::= 'empty'

list_first ::= 'first'

list_firstitem ::= 'firstItem'

list_hasindex ::= 'hasIndex(' index ')'

list_hasitem ::= 'hasItem(' item ')'

list_index ::= 'index(' item ')'

list_insert ::= 'insert(' item ( ',' index )? ')'

list_isempty ::= 'isEmpty'

list_items ::= 'items'

list_last ::= 'last'

list_lastitem ::= 'lastItem'

list_makearray ::= 'makeArray'

list_next ::= 'next(' index ')'

list_previous ::= 'previous(' index ')'

list_put ::= 'put(' item ',' index ')'

list_remove ::= 'remove(' index ')'

list_removeitem ::= 'removeItem(' item ')'

list_section ::= 'section(' start ',' items ')'

list_supplier ::= 'supplier'

properties_load ::= 'load(' source ')'

properties_new ::= 'new'

properties_putset ::= '{' name ']' '=' item

properties_getlogical ::= 'getLogical(' name ( ',' default )? ')'

properties_getproperty ::= 'getProperty(' name ( ',' default )? ')'

properties_getwhole ::= 'getWhole(' name ( ',' default )? ')'

properties_put ::= 'put(' item ',' name ')'

properties_save ::= 'save(' target ')'

properties_setlogical ::= 'setLogical(' name ',' value ')'

properties_setproperty ::= 'setProperty(' name ',' value ')'

properties_setwhole ::= 'setWhole(' name ',' value ')'

queue_new ::= 'new'

queue_of ::= 'of' ( '(' item ( ( ',' item )+ )? ')' )?

queue_atget ::= '[' index ']'

queue_putset ::= '[' index ']' '=' item

queue_allindexes ::= 'allIndexes'

queue_allitems ::= 'allItems'

queue_append ::= 'append(' item ')'

queue_at ::= 'at(' index ')'

queue_delete ::= 'delete(' index ')'

queue_empty ::= 'empty'

queue_first ::= 'first'

queue_firstitem ::= 'firstItem'

queue_hasindex ::= 'hasIndex(' index ')'

queue_hasitem ::= 'hasItem(' item ')'

queue_index ::= 'index(' item ')'

queue_insert ::= 'insert(' item ( ',' index )? ')'

queue_isempty ::= 'isEmpty'

queue_items ::= 'items'

queue_last ::= 'last'

queue_lastitem ::= 'lastItem'

queue_makearray ::= 'makeArray'

queue_next ::= 'next(' index ')'

queue_peek ::= 'peek'

queue_previous ::= 'previous(' index ')'

queue_pull ::= 'pull'

queue_push ::= 'push(' item ')'

queue_put ::= 'put(' item ',' index ')'

queue_queue ::= 'queue(' item ')'

queue_remove ::= 'remove(' index ')'

queue_removeitem ::= 'removeItem(' item ')'

queue_section ::= 'section(' start ',' items ')'

queue_supplier ::= 'supplier'

relation_new ::= 'new'

relation_atget ::= '[' index ']'

relation_putset ::= '[' index ']' '=' item

relation_allat ::= 'allAt(' index ')'

relation_allindex ::= 'allIndex(' item ')'

relation_allindexes ::= 'allIndexes'

relation_allitems ::= 'allItems'

relation_at ::= 'at(' index ')'

relation_difference ::= 'difference'

relation_empty ::= 'empty'

relation_hasindex ::= 'hasIndex(' index ')'

relation_hasitem ::= 'hasItem(' item ( ',' index )? ')'

relation_index ::= 'index(' item ')'

relation_intersection ::= 'intersection(' argument ')'

relation_isempty ::= 'isEmpty'

relation_items ::= 'items'

relation_makearray ::= 'makeArray'

relation_put ::= 'put(' item ',' index ')'

relation_remove ::= 'remove(' index ')'

relation_removeall ::= 'removeAll(' index ')'

relation_removeitem ::= 'removeItem(' item ( ',' index )? ')'

relation_subset ::= 'subset(' argument ')'

relation_supplier ::= 'supplier' ( '(' index ')' )?

relation_union ::= 'union' '(' index ')'

relation_uniqueindexes ::= 'uniqueIndexes'

relation_xor ::= 'xor(' argument ')'

set_of ::= 'of' ( '(' item ( ( ',' item )+ )? ')' )?

set_putset ::= '[' index ']' '=' item

set_hasitem ::= 'hasItem(' item ( ',' index )? ')'

set_intersection ::= 'intersection(' argument ')'

set_put ::= 'put(' item ',' index ')'

set_putall ::= 'putAll(' collection ')'

set_subset ::= 'subset(' argument ')'

set_union ::= 'union' '(' argument ')'

set_xor ::= 'xor(' argument ')'

stem_new ::= 'new' ( '(' name ')' )?

stem_atget ::= '[' index ']'

stem_putset ::= '[' index ']' '=' item

stem_allindexes ::= 'allIndexes'

stem_allitems ::= 'allItems'

stem_at ::= 'at(' tail ')'

stem_empty ::= 'empty'

stem_hasindex ::= 'hasIndex(' tail ')'

stem_hasitem ::= 'hasItem(' value ')'

stem_index ::= 'index(' item ')'

stem_isempty ::= 'isEmpty'

stem_items ::= 'items'

stem_makearray ::= 'makeArray'

stem_put ::= 'put(' item ',' tail ')'

stem_remove ::= 'remove(' tail ')'

stem_removeitem ::= 'removeItem(' item ')'

stem_request ::= 'request(' classid ')'

stem_supplier ::= 'supplier'

stem_todirectory ::= 'toDirextory'

stem_unknown ::= 'unknown(' messagename ',' messageargs ')'

table_new ::= 'new'

table_atget ::= '[' index ']'

table_putset ::= '[' index ']' '=' item

table_allindexes ::= 'allIndexes'

table_allitems ::= 'allItems'

table_at ::= 'at(' index ')'

table_empty ::= 'empty'

table_hasindex ::= 'hasIndex(' tail ')'

table_hasitem ::= 'hasItem(' value ')'

table_index ::= 'index(' item ')'

table_isempty ::= 'isempty'

table_items ::= 'items'

table_makearray ::= 'makeArray'

table_put ::= 'put(' item ',' index ')'

table_remove ::= 'remove(' index ')'

table_removeitem ::= 'removeItem(' item ')'

table_supplier ::= 'supplier'











