/* New in 5.0 */

rexxinfo_architecture ::= 'architecture'

rexxinfo_casesensitivefiles ::= 'casesensitiveFiles' 

rexxinfo_date ::= 'date' 

rexxinfo_digits ::= 'digits'

rexxinfo_directoryseparator ::= 'directorySeparator'

rexxinfo_endofline ::= 'endofline'

rexxinfo_form ::= 'form' 

rexxinfo_fuzz ::= 'fuzz'

rexxinfo_internaldigits ::= 'internalDigits'

rexxinfo_languagelevel ::= 'languageLevel'

rexxinfo_majorversion ::= 'majorVersion' 

rexxinfo_name ::= 'name' 

rexxinfo_package ::= 'package'

rexxinfo_pathseparator ::= 'pathSeparator' 

rexxinfo_platform ::= 'platform' 

rexxinfo_release ::= 'release' 

rexxinfo_revision ::= 'revision' 

rexxinfo_version ::= 'version'
