/* new in 5.0 - start */
alarmnotification_cancel    ::= 'cancel(' source ')'
alarmnotification_triggered ::= 'triggered(' source ')'

messagenotification_messagecomplete ::= 'messageComplete(' source ')'
/* new in 5.0 - end */


/* new in 5.0 */
alarm_attachment ::= 'attachment'

alarm_cancel ::= 'cancel'

/* new in 5.0 */
alarm_canceled ::= 'canceled' | 'cancelled'

/* chg in 5.0: changed "message" to (notification) "target" */
alarm_init ::= 'init(' atime ',' target (',' attachment)? ')'

/* new in 5.0 */
alarm_scheduledtime ::= 'scheduledTime'

/* new in 5.0 */
alarm_triggered ::= 'triggered'


/* new in 5.0 - start */
ticker_attachment ::= 'attachment'
ticker_cancel     ::= 'cancel'
ticker_canceled   ::= 'canceled' | 'cancelled'
ticker_init       ::= 'init(' interval ',' target (',' attachment)? ')'
ticker_interval   ::= 'interval'
/* new in 5.0 - end */


datetime_mindate ::= 'minDate'

datetime_maxdate ::= 'maxDate'

datetime_today ::= 'today(' offset? ')'

datetime_fromnormaldate ::= 'fromNormalDate(' date ',' separator? (',' offset)? ')'

datetime_fromeuropeandate ::= 'fromEuropeanDate(' date ',' separator? (',' offset)? ')'

datetime_fromordereddate ::= 'fromOrderedDate(' date ',' separator? (',' offset)? ')'

datetime_fromstandarddate ::= 'fromStandardDate(' date ',' separator? (',' offset)? ')'

datetime_fromusadate ::= 'fromUsaDate(' date ',' separator? (',' offset)? ')'

datetime_fromnormaltime ::= 'fromNormalTime(' time ( ',' offset )? ')'

datetime_fromciviltime ::= 'fromCivilTime(' time ( ',' offset )? ')'

datetime_fromlongtime ::= 'fromLongTime(' time ( ',' offset )? ')'

datetime_frombasedate ::= 'fromBaseDate(' date ( ',' offset )? ')'

datetime_fromticks ::= 'fromTicks(' time ( ',' offset )? ')'

datetime_fromisodate ::= 'fromIsoDate(' date ( ',' offset )? ')'

datetime_fromutcisodate ::= 'fromUtcIsoDate(' date ')'

/* keep four separate diagrams, so that the fourth can get split into two lines */
datetime_init1 ::= 'init'
datetime_init2 ::= 'init(' fulldate ( ',' offset )? ')'
datetime_init3 ::= 'init(' year ',' month ',' day ( ',' offset )? ')'
datetime_init4 ::= 'init(' year ',' month ',' day ',' hours ',' minutes ',' seconds
                          ',' microseconds? (',' offset)? ')'

datetime_arithmeticoperator ::= arithmetic_operator '(' argument ')'

datetime_compareto ::= 'compareTo(' other ')'

datetime_year ::= 'year'

datetime_month ::= 'month'

datetime_day ::= 'day'

datetime_hours ::= 'hours'

datetime_minutes ::= 'minutes'

datetime_seconds ::= 'seconds'

datetime_microseconds ::= 'microseconds'

datetime_dayminutes ::= 'dayMinutes'

datetime_dayseconds ::= 'daySeconds'

datetime_daymicroseconds ::= 'dayMicroseconds'

datetime_hashcode ::= 'hashCode'

datetime_addyears ::= 'addYears(' years ')'

datetime_addweeks ::= 'addWeeks(' weeks ')'

datetime_adddays ::= 'addDays(' days ')'

datetime_addhours ::= 'addHours(' hours ')'

datetime_addminutes ::= 'addMinutes(' minutes ')'

datetime_addseconds ::= 'addSeconds(' seconds ')'

datetime_addmicroseconds ::= 'addMicroseconds(' microseconds ')'

datetime_isodate ::= 'isoDate'

datetime_utcisodate ::= 'utcIsoDate'

datetime_basedate ::= 'baseDate'

datetime_yearday ::= 'yearDay'

datetime_weekday ::= 'weekDay'

datetime_europeandate ::= 'europeanDate(' ( separator )? ')'

datetime_languagedate ::= 'languageDate'

datetime_monthname ::= 'monthName'

datetime_dayname ::= 'dayName'

datetime_normaldate ::= 'normalDate(' ( separator )? ')'

datetime_ordereddate ::= 'orderedDate(' ( separator )? ')'

datetime_standarddate ::= 'standardDate(' ( separator )? ')'

datetime_usadate ::= 'usaDate(' ( separator )? ')'

datetime_civiltime ::= 'civiTime'

datetime_normaltime ::= 'normalTime'

datetime_longtime ::= 'longTime'

datetime_fulldate ::= 'fullDate'

datetime_utcdate ::= 'utcDate'

datetime_tolocaltime ::= 'toLocalTime'

datetime_toutctime ::= 'toUtcTime'

datetime_totimezone ::= 'toTimeZone(' ( offset )? ')'

datetime_ticks ::= 'ticks'

datetime_offset ::= 'offset'

datetime_date ::= 'date'

datetime_timeofday ::= 'timeofday'

datetime_elapsed ::= 'elapsed'

datetime_isleapyear ::= 'isLeapYear'

datetime_daysinmonth ::= 'daysInMonth'

datetime_daysinyear ::= 'daysInYear'

datetime_string ::= 'string'

timespan_fromdays ::= 'fromDays(' days ')'

timespan_fromhours ::= 'fromHours(' hours ')'

timespan_fromminutes ::= 'fromMinutes(' minutes ')'

timespan_fromseconds ::= 'fromSeconds(' seconds ')'

timespan_frommicroseconds ::= 'fromMicroseconds(' microseconds ')'

timespan_fromnormaltime ::= 'fromNormalTime(' time ')'

timespan_fromciviltime ::= 'fromCivilTime(' time ')'

timespan_fromlongtime ::= 'fromLongTime(' time ')'

timespan_fromstringformat ::= 'fromStringFormat(' time ')'

timespan_init ::= 'init(' fullDate ')'
timespan_init ::= 'init(' hours ',' minutes ',' seconds ')'
timespan_init ::= 'init(' days ',' hours ',' minutes ',' seconds ',' microseconds ')'

timespan_arithmeticoperator ::= arithmetic_operator '(' argument ')'

timespan_compareto ::= 'compareTo(' other ')'

timespan_duration ::= 'duration'

timespan_days ::= 'days'

timespan_hours ::= 'hours'

timespan_minutes ::= 'minutes'

timespan_seconds ::= 'seconds'

timespan_microseconds ::= 'microseconds'

timespan_totaldays ::= 'totalDays'

timespan_totalhours ::= 'totalHours'

timespan_totalminutes ::= 'totalMinutes'

timespan_totalseconds ::= 'totalSeconds'

timespan_totalmicroseconds ::= 'totalMicroseconds'

timespan_hashcode ::= 'hashCode'

timespan_addweeks ::= 'addWeeks(' weeks ')'

timespan_adddays ::= 'addDays(' days ')'

timespan_addhours ::= 'addHours(' hours ')'

timespan_addminutes ::= 'addMinutes(' minutes ')'

timespan_addseconds ::= 'addSeconds(' seconds ')'

timespan_addmicroseconds ::= 'addMicroseconds(' microseconds ')'

timespan_sign ::= 'sign'

timespan_string ::= 'string'

comparable_compareto ::= 'compareTo(' other ')'

orderable_comparisonoperator ::= 'comparison_operator(' argument ')'
orderable_compareto ::= 'compareTo(' other ')'

comparator_compare ::= 'compare(' first ',' second ')'

caselesscomparator_compare ::= 'compare(' first ',' second ')'

columncomparator_compare ::= 'compare(' first ',' second ')'

columncomparator_init ::= 'init(' start ',' length ')'

caselesscolumncomparator_compare ::= 'compare(' first ',' second ')'

caselesscolumncomparator_init ::= 'init(' start ',' length ')'

descendingcomparator_compare ::= 'compare(' first ',' second ')'

caselessdescendingcomparator_compare ::= 'compare(' first ',' second ')'

invertingcomparator_compare ::= 'compare(' first ',' second ')'

invertingcomparator_init ::= 'init(' comparator ')'

numericcomparator_compare ::= 'compare(' first ',' second ')'

numericcomparator_init ::= 'init(' ( digits )? ')'

monitor_current ::= 'current'

monitor_destination ::= 'destination(' destination? ')'

monitor_init ::= 'init(' destination? ')'

monitor_unknown ::= 'unknown(' messagename ',' messageargs ')'

/* MutableBuffer: see mutablebuffer.ebnf */

regexp_init ::= 'init(' pattern ( ',' ( '"Maximal"' | '"Minimal"' ) )? ')'

regexp_match ::= 'match(' string ')'

regexp_parse ::= 'parse(' pattern ( ',' ( '"Current"' | '"Maximal"' | '"Minimal"' ) )? ')'

regexp_pos ::= 'pos(' haystack ')'

regexp_position ::= 'position'

rexxqueue_create ::= 'create(' name ')'

rexxqueue_delete_class ::= 'delete(' name ')'

rexxqueue_exists ::= 'exists(' name ')'

rexxqueue_open ::= 'open(' name ')'

rexxqueue_delete ::= 'delete'

rexxqueue_empty ::= 'empty'

rexxqueue_get ::= 'get'

rexxqueue_init ::= 'init(' ( name )? ')'

rexxqueue_linein ::= 'linein'

rexxqueue_lineout ::= 'lineout(' ( line )? ')'

rexxqueue_makearray ::= 'makearray'

rexxqueue_pull ::= 'pull'

rexxqueue_push ::= 'push(' ( line )? ')'

rexxqueue_queue ::= 'queue(' ( line )? ')'

rexxqueue_queued ::= 'queued'

rexxqueue_say ::= 'say(' ( line )? ')'

rexxqueue_set ::= 'set(' name ')'

supplier_new ::= 'new(' items ',' indexes ')'

supplier_allindexes ::= 'allIndexes'

supplier_allitems ::= 'allItems'

supplier_available ::= 'available'

supplier_index ::= 'index'

supplier_init ::= 'init'

supplier_item ::= 'item'

supplier_next ::= 'next'

supplier_supplier ::= 'supplier'

streamsupplier_available ::= 'available'

streamsupplier_index ::= 'index'

streamsupplier_init ::= 'init'

streamsupplier_item ::= 'item'

streamsupplier_next ::= 'next'

rexxcontext_args ::= 'args'

rexxcontext_condition ::= 'condition'

rexxcontext_digits ::= 'digits'

rexxcontext_executable ::= 'executable'

rexxcontext_form ::= 'form'

rexxcontext_fuzz ::= 'fuzz'

rexxcontext_line ::= 'line'

rexxcontext_name ::= 'name'

rexxcontext_package ::= 'package'

rexxcontext_rs ::= 'rs'

rexxcontext_stackframes ::= 'stackFrames'

rexxcontext_variables ::= 'variables'

stackframe_arguments ::= 'arguments'

stackframe_executable ::= 'executable'

stackframe_line ::= 'line'

stackframe_makestring ::= 'makeString'

stackframe_name ::= 'name'

stackframe_string ::= 'string'

stackframe_target ::= 'target'

stackframe_traceline ::= 'traceLine'

stackframe_type ::= 'type'

weakreference_new ::= 'new(' object ')'

weakreference_value ::= 'value'

pointer_new ::= 'new'

pointer_comparisonoperator ::= 'comparison_operator(' argument ')'

pointer_isnull ::= 'isNull'

buffer_new ::= 'new'

file_iscasesensitive ::= 'isCaseSensitive'

file_listroots ::= 'listRoots'

file_pathseparator ::= 'pathSeparator'

file_separator ::= 'separator'

file_absolutefile ::= 'absoluteFile'

file_absolutepath ::= 'absolutePath'

file_canread ::= 'canRead'

file_canwrite ::= 'canWrite'

file_compareto ::= 'compareTo(' other ')'

file_delete ::= 'delete'

file_exists ::= 'exists'

file_hashcode ::= 'hashCode'

file_init ::= 'init(' path ( ',' dir )? ')'

file_isdirectory ::= 'isDirectory'

file_isfile ::= 'isFile'

file_ishidden ::= 'isHidden'

file_lastmodified ::= 'lastModified'
file_lastmodified ::= 'lastModified' '=' date

file_length ::= 'length'

file_list ::= 'list'

file_listfiles ::= 'listFiles'

file_makedir ::= 'makeDir'

file_makedirs ::= 'makeDirs'

file_name ::= 'name'

file_parent ::= 'parent'

file_parentfile ::= 'parentFile'

file_path ::= 'path'

file_renameto ::= 'renameTo(' dest ')'

file_setreadonly ::= 'setReadOnly'

file_string ::= 'string'


/* new in 5.0 - start */
rexxinfo_architecture       ::= 'architecture'
rexxinfo_casesensitivefiles ::= 'caseSensitiveFiles' 
rexxinfo_date               ::= 'date' 
rexxinfo_digits             ::= 'digits'
rexxinfo_directoryseparator ::= 'directorySeparator'
rexxinfo_endofline          ::= 'endofline'
rexxinfo_form               ::= 'form' 
rexxinfo_fuzz               ::= 'fuzz'
rexxinfo_internaldigits     ::= 'internalDigits'
rexxinfo_languagelevel      ::= 'languageLevel'
rexxinfo_majorversion       ::= 'majorVersion' 
rexxinfo_name               ::= 'name' 
rexxinfo_package            ::= 'package'
rexxinfo_pathseparator      ::= 'pathSeparator' 
rexxinfo_platform           ::= 'platform' 
rexxinfo_release            ::= 'release' 
rexxinfo_revision           ::= 'revision' 
rexxinfo_version            ::= 'version'
/* new in 5.0 - start */
