datetime_mindate ::= 'minDate'

datetime_maxdate ::= 'maxDate'

datetime_today ::= 'today'

datetime_fromnormaldate ::= 'fromNormalDate(' date ( ',' ( separator )? ( ',' offset )? )? ')'

datetime_fromeuropeandate ::= 'fromEuropeanDate(' date ( ',' ( separator )? ( ',' offset )? )? ')'

datetime_fromordereddate ::= 'fromOrderedDate(' date ( ',' ( separator )? ( ',' offset )? )? ')'

datetime_fromstandarddate ::= 'fromStandardDate(' date ( ',' ( separator )? ( ',' offset )? )? ')'

datetime_fromusadate ::= 'fromUsaDate(' date ( ',' ( separator )? ( ',' offset )? )? ')'

datetime_fromnormaltime ::= 'fromNormalTime(' time ( ',' offset )? ')'

datetime_fromciviltime ::= 'fromCivilTime(' time ( ',' offset )? ')'

datetime_fromlongtime ::= 'fromLongTime(' time ( ',' offset )? ')'

datetime_frombasedate ::= 'fromBaseDate(' date ( ',' offset )? ')'

datetime_fromticks ::= 'fromTicks(' time ( ',' offset )? ')'

datetime_fromisodate ::= 'fromIsoDate(' date ( ',' offset )? ')'

datetime_fromutcisodate ::= 'fromUtcIsoDate(' date ')'

datetime_init ::= 'init'

datetime_init2 ::= 'init(' fulldate ( ',' offset )? ')'

datetime_init3 ::= 'init(' year ',' month ',' day ( ',' offset )? ')'

datetime_init4 ::= 'init(' year ',' month ',' day ',' hours ',' minutes ',' seconds
                          ( ',' ( microseconds )? ( ',' offset )? )? ')'
datetime_arithmeticoperator ::= arithmetic_operator '(' argument ')'

datetime_compareto ::= 'compareTo(' other ')'

datetime_year ::= 'year'

datetime_month ::= 'month'

datetime_day ::= 'day'

datetime_hours ::= 'hours'

datetime_minutes ::= 'minutes'

datetime_seconds ::= 'seconds'

datetime_microseconds ::= 'microseconds'

datetime_dayminutes ::= 'dayMinutes'

datetime_dayseconds ::= 'daySeconds'

datetime_daymicroseconds ::= 'dayMicroseconds'

datetime_hashcode ::= 'hashCode'

datetime_addyears ::= 'addYears(' years ')'

datetime_addweeks ::= 'addWeeks(' weeks ')'

datetime_adddays ::= 'addDays(' days ')'

datetime_addhours ::= 'addHours(' hours ')'

datetime_addminutes ::= 'addMinutes(' minutes ')'

datetime_addseconds ::= 'addSeconds(' seconds ')'

datetime_addmicroseconds ::= 'addMicroseconds(' microseconds ')'

datetime_isodate ::= 'isoDate'

datetime_utcisodate ::= 'utcIsoDate'

datetime_basedate ::= 'baseDate'

datetime_yearday ::= 'yearDay'

datetime_weekday ::= 'weekDay'

datetime_europeandate ::= 'europeanDate(' ( separator )? ')'

datetime_languagedate ::= 'languageDate'

datetime_monthname ::= 'monthName'

datetime_dayname ::= 'dayName'

datetime_normaldate ::= 'normalDate(' ( separator )? ')'

datetime_ordereddate ::= 'orderedDate(' ( separator )? ')'

datetime_standarddate ::= 'standardDate(' ( separator )? ')'

datetime_usadate ::= 'usaDate(' ( separator )? ')'

datetime_civiltime ::= 'civiTime'

datetime_normaltime ::= 'normalTime'

datetime_longtime ::= 'longTime'

datetime_fulldate ::= 'fullDate'

datetime_utcdate ::= 'utcDate'

datetime_tolocaltime ::= 'toLocalTime'

datetime_toutctime ::= 'toUtcTime'

datetime_totimezone ::= 'toTimeZone(' ( offset )? ')'

datetime_ticks ::= 'ticks'

datetime_offset ::= 'offset'

datetime_date ::= 'date'

datetime_timeofday ::= 'timeofday'

datetime_elapsed ::= 'elapsed'

datetime_isleapyear ::= 'isLeapYear'

datetime_dayinmonth ::= 'dayInMonth'

datetime_daysinyear ::= 'daysInYear'

datetime_string ::= 'string'




