datetime_mindate ::= 'minDate'

datetime_maxdate ::= 'maxDate'

datetime_today ::= 'today'

datetime_fromnormaldate ::= 'fromNormalDate(' date ( ',' ( separator )? ( ',' offset )? )? ')'

datetime_fromeuropeandate ::= 'fromEuropeanDate(' date ( ',' ( separator )? ( ',' offset )? )? ')'

datetime_fromordereddate ::= 'fromOrderedDate(' date ( ',' ( separator )? ( ',' offset )? )? ')'

datetime_fromstandarddate ::= 'fromStandardDate(' date ( ',' ( separator )? ( ',' offset )? )? ')'

datetime_fromusadate ::= 'fromUsaDate(' date ( ',' ( separator )? ( ',' offset )? )? ')'

datetime_fromnormaltime ::= 'fromNormalTime(' time ( ',' offset )? ')'

datetime_fromciviltime ::= 'fromCivilTime(' time ( ',' offset )? ')'

datetime_fromlongtime ::= 'fromLongTime(' time ( ',' offset )? ')'

datetime_frombasedate ::= 'fromBaseDate(' date ( ',' offset )? ')'

datetime_fromticks ::= 'fromTicks(' time ( ',' offset )? ')'

datetime_fromisodate ::= 'fromIsoDate(' date ( ',' offset )? ')'

datetime_fromutcisodate ::= 'fromUtcIsoDate(' date ')'

datetime_init ::= 'init'

datetime_init2 ::= 'init(' fulldate ( ',' offset )? ')'

datetime_init3 ::= 'init(' year ',' month ',' day ( ',' offset )? ')'

datetime_init4 ::= 'init(' year ',' month ',' day ',' hours ',' minutes ',' seconds
                          ( ',' ( microseconds )? ( ',' offset )? )? ')'
datetime_arithmeticoperator ::= arithmetic_operator '(' argument ')'

datetime_compareto ::= 'compareTo(' other ')'

datetime_year ::= 'year'

datetime_month ::= 'month'

datetime_day ::= 'day'

datetime_hours ::= 'hours'

datetime_minutes ::= 'minutes'

datetime_seconds ::= 'seconds'

datetime_microseconds ::= 'microseconds'

datetime_dayminutes ::= 'dayMinutes'

datetime_dayseconds ::= 'daySeconds'

datetime_daymicroseconds ::= 'dayMicroseconds'

datetime_hashcode ::= 'hashCode'

datetime_addyears ::= 'addYears(' years ')'

datetime_addweeks ::= 'addWeeks(' weeks ')'

datetime_adddays ::= 'addDays(' days ')'

datetime_addhours ::= 'addHours(' hours ')'

datetime_addminutes ::= 'addMinutes(' minutes ')'

datetime_addseconds ::= 'addSeconds(' seconds ')'

datetime_addmicroseconds ::= 'addMicroseconds(' microseconds ')'

datetime_isodate ::= 'isoDate'

datetime_utcisodate ::= 'utcIsoDate'

datetime_basedate ::= 'baseDate'

datetime_yearday ::= 'yearDay'

datetime_weekday ::= 'weekDay'

datetime_europeandate ::= 'europeanDate(' ( separator )? ')'

datetime_languagedate ::= 'languageDate'

datetime_monthname ::= 'monthName'

datetime_dayname ::= 'dayName'

datetime_normaldate ::= 'normalDate(' ( separator )? ')'

datetime_ordereddate ::= 'orderedDate(' ( separator )? ')'

datetime_standarddate ::= 'standardDate(' ( separator )? ')'

datetime_usadate ::= 'usaDate(' ( separator )? ')'

datetime_civiltime ::= 'civiTime'

datetime_normaltime ::= 'normalTime'

datetime_longtime ::= 'longTime'

datetime_fulldate ::= 'fullDate'

datetime_utcdate ::= 'utcDate'

datetime_tolocaltime ::= 'toLocalTime'

datetime_toutctime ::= 'toUtcTime'

datetime_totimezone ::= 'toTimeZone(' ( offset )? ')'

datetime_ticks ::= 'ticks'

datetime_offset ::= 'offset'

datetime_date ::= 'date'

datetime_timeofday ::= 'timeofday'

datetime_elapsed ::= 'elapsed'

datetime_isleapyear ::= 'isLeapYear'

datetime_dayinmonth ::= 'dayInMonth'

datetime_daysinyear ::= 'daysInYear'

datetime_string ::= 'string'

alarm_cancel ::= 'cancel'

alarm_init ::= 'init(' attime ',' message ')'

timespan_fromdays ::= 'fromDays(' days ')'

timespan_fromhours ::= 'fromHours(' hours ')'

timespan_fromminutes ::= 'fromMinutes(' minutes ')'

timespan_fromseconds ::= 'fromSeconds(' seconds ')'

timespan_frommicroseconds ::= 'fromMicroseconds(' microseconds ')'

timespan_fromnormaltime ::= 'fromNormalTime(' time ')'

timespan_fromciviltime ::= 'fromCivilTime(' time ')'

timespan_fromlongtime ::= 'fromLongTime(' time ')'

timespan_fromstringformat ::= 'fromStringFormat(' time ')'

timespan_init1 ::= 'init(' fullDate ')'

timespan_init2 ::= 'init(' hours ',' minutes ',' seconds ')'

timespan_init3 ::= 'init(' days ',' hours ',' minutes ',' seconds ',' microseconds ')'

timespan_arithmeticoperator ::= 'arithmetic_operator(' argument ')'

timespan_compareto ::= 'compareTo(' other ')'

timespan_duration ::= 'duration'

timespan_days ::= 'days'

timespan_hours ::= 'hours'

timespan_minutes ::= 'minutes'

timespan_seconds ::= 'seconds'

timespan_microseconds ::= 'microseconds'

timespan_toyaldays ::= 'totalDays'

timespan_totalhours ::= 'totalHours'

timespan_totalminutes ::= 'totalMinutes'

timespan_totalseconds ::= 'totalSeconds'

timespan_totalmicroseconds ::= 'totalMicroseconds'

timespan_hashcode ::= 'hashCode'

timespan_addweeks ::= 'addWeeks(' weeks ')'

timespan_adddays ::= 'addDays(' days ')'

timespan_addhours ::= 'addHours(' hours ')'

timespan_addminutes ::= 'addMinutes(' minutes ')'

timespan_addseconds ::= 'addSeconds(' seconds ')'

timespan_addmicroseconds ::= 'addMicroseconds(' microseconds ')'

timespan_sign ::= 'sign'

timespan_string ::= 'string'

comparable_compareto ::= 'compareTo(' other ')'

orderable_comparisonoperator ::= 'comparison_operator(' argument ')'

comparator_compare ::= 'compare(' first ',' second ')'

caselesscomparator_compare ::= 'compare(' first ',' second ')'

columncomparator_compare ::= 'compare(' first ',' second ')'

columncomparator_init ::= 'init(' start ',' length ')'

caselesscolumncomparator_compare ::= 'compare(' first ',' second ')'

caselesscolumncomparator_init ::= 'init(' start ',' length ')'

descendingcomparator_compare ::= 'compare(' first ',' second ')'

caselessdescendingcomparator_compare ::= 'compare(' first ',' second ')'

invertingcomparator_compare ::= 'compare(' first ',' second ')'

invertingcomparator_init ::= 'init(' comparator ')'

numericcomparator_compare ::= 'compare(' first ',' second ')'

numericcomparator_init ::= 'init(' ( digits )? ')'

monitor_current ::= 'current'

monitor_destination ::= 'destination' ( '(' destination ')' )?

monitor_init ::= 'init' ( '(' destination ')' )?

monitor_unknown ::= 'unknown(' messagename ',' messageargs ')'

mutablrbuffer_new ::= 'new(' ( string )? ( ',' buffersize )? ')'

mutablrbuffer_append ::= 'append(' string ')'

mutablrbuffer_caselesschangestr ::= 'caselessChangeStr(' needle ',' newneedle ( ',' count )? ')'

mutablrbuffer_caselesscountstr ::= 'caselessCountStr(' needle ')'

mutablrbuffer_caselesslastpos ::= 'caselessLastPos(' needle ( ',' ( start )? ( ',' length )? )? ')'

mutablrbuffer_caselessmatch ::= 'caselessMatch(' start ',' other ( ',' ( n )? ( ',' length )? )? ')'

mutablrbuffer_caselessmatchchar ::= 'caselessMatchChar(' n ',' chars ')'

mutablrbuffer_caselesspos ::= 'caselessPos(' needle ( ',' ( start )? ( ',' length )? )? ')'

mutablrbuffer_caselesswordpos ::= 'caselessWordPos(' phrase ( ',' start )? ')'

mutablrbuffer_changestr ::= 'changeStr(' needle ',' newneedle ( ',' count )? ')'

mutablrbuffer_countstr ::= 'countStr(' needle ')'

mutablrbuffer_delete ::= 'delete(' n ( ',' length )? ')'

mutablrbuffer_delstr ::= 'delStr(' n ( ',' length )? ')'

mutablrbuffer_delword ::= 'delWord(' n ( ',' length )? ')'

mutablrbuffer_getbuffersize ::= 'getBufferSize'

mutablrbuffer_insert ::= 'insert(' new ( ',' ( n )? ( ',' ( length )? ( ',' pad )? )? )? ')'

mutablrbuffer_lastpos ::= 'lastPos(' needle ( ',' start )? ')'

mutablrbuffer_length ::= 'length'

mutablrbuffer_lower ::= 'lower(' ( n )? ( ',' length )? ')'

mutablrbuffer_makearray ::= 'makeArray(' ( separator )? ')'

mutablrbuffer_match ::= 'match(' start ',' other ( ',' ( n )? ( ',' length )? )? ')'

mutablrbuffer_matchchar ::= 'matchChar(' n ',' chars ')'

mutablrbuffer_overlay ::= 'overlay(' new ( ',' ( n )? ( ',' ( length )? ( ',' pad )? )? )? ')'

mutablrbuffer_pos ::= 'pos(' needle ( ',' start )? ')'

mutablrbuffer_replaceat ::= 'replaceatAt(' new ',' n ( ',' ( length )? ( ',' pad )? )? ')'

mutablrbuffer_setbuffersize ::= 'setBufferSize(' n ')'

mutablrbuffer_space ::= 'space' ( '(' n ( ',' pad )? ')' )?

mutablrbuffer_string ::= 'string'

mutablrbuffer_subchar ::= 'subChar(' n ')'

mutablrbuffer_substr ::= 'substr(' n ( ',' ( length )? ( ',' pad )? )? ')'

mutablrbuffer_subword ::= 'subWord(' n ( ',' length )? ')'

mutablrbuffer_subwords ::= 'subWords(' ( n )? ( ',' length )? ')'

mutablebuffer_translate ::= 'translate(' ( ( tableo ( ',' ( tablei ( ',' pad )? )? )? | 
                                          n ( ',' length )? ) )? ')'

mutablrbuffer_upper ::= 'upper(' ( n )? ( ',' length )? ')'

mutablrbuffer_verify ::= 'verify(' reference ( ',' ( option )? ( ',' ( start )? ( ',' length )? )? )? ')'

mutablrbuffer_word ::= 'word(' n ')'

mutablrbuffer_wordindex ::= 'wordIndex(' n ')'

mutablrbuffer_wordlength ::= 'wordLength(' n ')'

mutablrbuffer_wordpos ::= 'wordPos(' phrase ( ',' start )? ')'

mutablrbuffer_words ::= 'words'
