csvstream_close ::= 'close'

csvstream_csvlinein ::= 'csvlinein'

csvstream_csvlineout ::= 'csvlineout(' collection_object ')'

csvstream_getheaders ::= 'getheaders'

csvstream_init ::= 'init(' name ',' headers_exist? ')'

csvstream_setheaders ::= 'setheaders(' header_obj ')'

