files_sysaccess ::= 'SysAccess(' file ',' mode ')'

files_syschmod ::= 'SysChmod(' file ',' mode ')'

files_syschown ::= 'SysChown(' srcpath ',' uid ',' gid ')'

files_syschroot ::= 'SysChroot(' srcpath ')'

files_sysclose ::= 'SysClose(' fh ')'

files_syseuidaccess ::= 'SysEuidaccess(' file ',' mode ')'

files_sysgetdirlist ::= 'SysGetDirList(' dir ')'

files_syslchown ::= 'SysLchown(' srcpath ',' uid ',' gid ')'

files_syslink ::= 'SysLink(' srcpath ',' targetpath ')'

files_sysmkdir ::= 'SysMkdir(' dir ',' mode ')'

files_sysrmdir ::= 'SysRmdir(' dir ')'

files_sysstat ::= 'SysStat(' file ',' option ')'

files_syssymlink ::= 'SysSymlink(' srcpath ',' targetpath ')'

files_sysumask ::= 'SysUmask(' umask ')'

files_sysuname ::= 'SysUname(' option ')'

files_sysunlink ::= 'SysUnLink(' srcpath ')'

files_syswordexp ::= 'SysWordexp(' option ')'

misc_syscrypt ::= 'SysCrypt(' str ',' salt ')'

misc_sysgetsid ::= 'SysGetSID(' ('0' | pid) ')'

misc_sysgeterrno ::= 'SysGetErrno()'

misc_sysgeterrnomsg ::= 'SysGetErrnoMsg(' errno ')'

misc_sysgetsizeofptr ::= 'SysGetsizeofptr()'

misc_syssetsid ::= 'SysSetsid()'

misc_syssignal ::= 'SysSignal(' signum ',' option ')'

namelookup_sysgethostname ::= 'SysGethostname()'

namelookup_sysgetservbyname ::= 'SysGetservbyname(' name ',' proto ',' option ')'

namelookup_sysgetservbyport ::= 'SysGetservbyport(' port ',' proto ',' option ')'

namelookup_sysgettzname1 ::= 'SysGettzname1()'

namelookup_sysgettzname2 ::= 'SysGettzname2()'

process_sysgetpid ::= 'SysGetpid()'

process_sysgetppid ::= 'SysGetppid()'

process_sysgettid ::= 'SysGettid()'

process_syskill ::= 'SysKill(' pid ',' sig ')'

usergrps_sysgetegid ::= 'SysGetegid()'

usergrps_sysgeteuid ::= 'SysGeteuid()'

usergrps_sysgetgid ::= 'SysGetgid()'

usergrps_sysgetgrgid ::= 'SysGetgrgid()'

usergrps_sysgetgrnam ::= 'SysGetgrnam(' grpname ',' option ')'

usergrps_sysgetpgrp ::= 'SysGetpgrp()'

usergrps_sysgetpwnam ::= 'SysGetpwnam(' username ',' option ')'

usergrps_sysgetpwuid ::= 'SysGetpwuid(' uid ',' option ')'

usergrps_sysgetuid ::= 'SysGetuid()'

usergrps_syssetegid ::= 'SysSetegid(' gid ')'

usergrps_sysseteuid ::= 'SysSeteuid(' euid ')'

usergrps_syssetgid ::= 'SysSetgid(' gid ')'

usergrps_syssetpgid ::= 'SysSetpgid(' pid ',' pgid ')'

usergrps_syssetpgrp ::= 'SysSetpgrp()'

usergrps_syssetuid ::= 'SysSetuid(' uid ')'

xattr_sysgetxattr ::= 'SysGetxattr(' fname ',' xname ')'

xattr_syslistxattr ::= 'SysListxattr(' fname ')'

xattr_sysremovexattr ::= 'SysRemovexattr(' fname ',' xname ')'

xattr_syssetxattr ::= 'SysSetxattr(' fname ',' xname ',' val ')'

