mimepart_new ::= 'new(' type? ')'

mimepart_addcontent ::= 'addContent(' string ')'

mimepart_crlf ::= 'crlf'

mimepart_content ::= 'content'

mimepart_description ::= 'description'
mimepart_description ::= 'description' '=' newdescription

mimepart_disposition ::= 'disposition'
mimepart_disposition ::= 'disposition' '=' newdisposition

mimepart_encoding ::= 'encoding'
mimepart_encoding ::= 'encoding' '=' newencoding

mimepart_id ::= 'id'
mimepart_id ::= 'id' '=' newid

mimepart_string ::= 'string'

mimepart_type ::= 'type'
mimepart_type ::= 'type' '=' newtype

mimemultipart_new ::= 'new(' type? ')'

mimemultipart_addpart ::= 'addPart(' part ')'

mimemultipart_crlf ::= 'crlf'

mimemultipart_description ::= 'description'
mimemultipart_description ::= 'description' '=' newdescription

mimemultipart_disposition ::= 'disposition'
mimemultipart_disposition ::= 'disposition' '=' newdisposition

mimemultipart_encoding ::= 'encoding'
mimemultipart_encoding ::= 'encoding' '=' newencoding

mimemultipart_id ::= 'id'
mimemultipart_id ::= 'id' '=' newid

mimemultipart_string ::= 'string'

mimemultipart_type ::= 'type'
mimemultipart_type ::= 'type' '=' newtype   

