funcs_mathloadfuncs ::= 'MathLoadFuncs()'

funcs_mathdropfuncs ::= 'MathDropFuncs()'

funcs_rxcalcsqrt ::= 'RxCalcSqrt(' number ( ',' precision )? ')'

funcs_rxcalcexp ::= 'RxCalcExp(' number ( ',' precision )? ')'

funcs_rxcalclog ::= 'RxCalcLog(' number ( ',' precision )? ')'

funcs_rxcalclog10 ::= 'RxCalcLog10(' number ( ',' precision )? ')'

funcs_rxcalcsinh ::= 'RxCalcSinH(' number ( ',' precision )? ')'

funcs_rxcalccosh ::= 'RxCalcCosH(' number ( ',' precision )? ')'

funcs_rxcalctanh ::= 'RxCalcTanH(' number ( ',' precision )? ')'

funcs_rxcalcpower ::= 'RxCalcPower(' number1 ',' number2 ( ',' precision )? ')'

funcs_rxcalcsin ::= 'RxCalcSin(' number ( ',' precision ( ', "D"' | ', "R"' | ', "G"' )? )? ')'

funcs_rxcalccos ::= 'RxCalcCos(' number ( ',' precision ( ', "D"' | ', "R"' | ', "G"' )? )? ')'

funcs_rxcalctan ::= 'RxCalcTan(' number ( ',' precision ( ', "D"' | ', "R"' | ', "G"' )? )? ')'

funcs_rxcalccotan ::= 'RxCalcCotan(' number ( ',' precision ( ', "D"' | ', "R"' | ', "G"' )? )? ')'

funcs_rxcalcpi ::= 'RxCalcPi(' ( precision )? ')'

funcs_rxcalcarcsin ::= 'RxCalcArcSin(' number ( ',' precision ( ', "D"' | ', "R"' | ', "G"' )? )? ')'

funcs_rxcalcarccos ::= 'RxCalcArcCos(' number ( ',' precision ( ', "D"' | ', "R"' | ', "G"' )? )? ')'

funcs_rxcalcarctan ::= 'RxCalcArcTab(' number ( ',' precision ( ', "D"' | ', "R"' | ', "G"' )? )? ')'

