/*----------------------------------------------------------------------------*/
/*                                                                            */
/* Copyright (c) 2008 Rexx Language Association. All rights reserved.         */
/*                                                                            */
/* This program and the accompanying materials are made available under       */
/* the terms of the Common Public License v1.0 which accompanies this         */
/* distribution. A copy is also available at the following address:           */
/* http://www.oorexx.org/license.html                                         */
/*                                                                            */
/* Redistribution and use in source and binary forms, with or                 */
/* without modification, are permitted provided that the following            */
/* conditions are met:                                                        */
/*                                                                            */
/* Redistributions of source code must retain the above copyright             */
/* notice, this list of conditions and the following disclaimer.              */
/* Redistributions in binary form must reproduce the above copyright          */
/* notice, this list of conditions and the following disclaimer in            */
/* the documentation and/or other materials provided with the distribution.   */
/*                                                                            */
/* Neither the name of Rexx Language Association nor the names                */
/* of its contributors may be used to endorse or promote products             */
/* derived from this software without specific prior written permission.      */
/*                                                                            */
/* THIS SOFTWARE IS PROVIDED BY THE COPYright HOLDERS AND CONTRIBUTORS        */
/* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT          */
/* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS          */
/* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYright   */
/* OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,      */
/* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED   */
/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,        */
/* OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY     */
/* OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING    */
/* NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS         */
/* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.               */
/*                                                                            */
/*----------------------------------------------------------------------------*/


::class 'METHODtester' public

-- These are the real external functions we are testing
::method tstargs000 EXTERNAL "LIBRARY orxmethod TstArgs000"
::method tstargs001 EXTERNAL "LIBRARY orxmethod TstArgs001"
::method tstargs002 EXTERNAL "LIBRARY orxmethod TstArgs002"
::method tstargs003 EXTERNAL "LIBRARY orxmethod TstArgs003"
::method tstargs004 EXTERNAL "LIBRARY orxmethod TstArgs004"
::method tstargs005 EXTERNAL "LIBRARY orxmethod TstArgs005"
::method tstargs006 EXTERNAL "LIBRARY orxmethod TstArgs006"
::method tstargs007 EXTERNAL "LIBRARY orxmethod TstArgs007"
::method tstargs008 EXTERNAL "LIBRARY orxmethod TstArgs008"
::method tstargs009 EXTERNAL "LIBRARY orxmethod TstArgs009"
::method tstargs010 EXTERNAL "LIBRARY orxmethod TstArgs010"
::method tstargs011 EXTERNAL "LIBRARY orxmethod TstArgs011"
::method tstargs012 EXTERNAL "LIBRARY orxmethod TstArgs012"
::method tstargs013 EXTERNAL "LIBRARY orxmethod TstArgs013"
::method tstargs014 EXTERNAL "LIBRARY orxmethod TstArgs014"
::method tstargs015 EXTERNAL "LIBRARY orxmethod TstArgs015"
::method tstargs016 EXTERNAL "LIBRARY orxmethod TstArgs016"
::method tstargs017 EXTERNAL "LIBRARY orxmethod TstArgs017"
::method tstargs018 EXTERNAL "LIBRARY orxmethod TstArgs018"
::method tstargs019 EXTERNAL "LIBRARY orxmethod TstArgs019"
::method tstargs020 EXTERNAL "LIBRARY orxmethod TstArgs020"
::method tstargs021 EXTERNAL "LIBRARY orxmethod TstArgs021"
::method tstargs022 EXTERNAL "LIBRARY orxmethod TstArgs022"
::method tstargs023 EXTERNAL "LIBRARY orxmethod TstArgs023"
::method tstargs024 EXTERNAL "LIBRARY orxmethod TstArgs024"
::method tstargs025a EXTERNAL "LIBRARY orxmethod TstArgs025a"
::method tstargs025b EXTERNAL "LIBRARY orxmethod TstArgs025b"
::method tstargs025c EXTERNAL "LIBRARY orxmethod TstArgs025c"

