methods_ftpannotatelog ::= 'ftpAnnotateLog(' line ')'

methods_ftpappend ::= 'ftpAppend(' localfilename ',' remotefilename ( ',' mode )? ')'

methods_ftpchdir ::= 'ftpChDir(' newdir ')'

methods_ftpdelete ::= 'ftpDelete(' filename ')'

methods_ftpdir ::= 'ftpDir(' pattern ')'

methods_ftpget ::= 'ftpGet(' localfilename ',' remotefilename ( ',' mode )? ')'

methods_ftpgetmode ::= 'ftpGetMode()'

methods_ftpgettype ::= 'ftpGetType()'

methods_ftplogoff ::= 'ftpLogoff()'

methods_ftpls ::= 'ftpLs(' pattern ')'

methods_ftpmkdir ::= 'ftpMkDir(' newdir ')'

methods_ftpput ::= 'ftpPut(' localfilename ',' remotefilename ( ',' mode )? ')'

methods_ftpputunique ::= 'ftpPutUnique(' localfilename ',' remotefilename ( ',' mode )? ')'

methods_ftppwd ::= 'ftpPwd()'

methods_ftpquote ::= 'ftpQuote(' cmd ')'

methods_ftprename ::= 'ftpRename(' oldfile ',' newfile ')'

methods_ftprmdir ::= 'ftpRmDir(' newdir ')'

methods_ftpsetmode ::= 'ftpSetMode(' ( 'PASSIVE' | 'ACTIVE') ')'

methods_ftpsettype ::= 'ftpSetType(' ( 'ASCII' | 'BINARY') ')'

methods_ftpsetuser ::= 'ftpSetUser(' host ',' user
                                                  ( ',' ( password )? ( ',' acct )? )? ')'

methods_ftpsite ::= 'ftpSite(' cmd ')'

methods_ftpsys ::= 'ftpSys()'

methods_ftptrace ::= 'ftpTrace()'

methods_ftptracelog ::= 'ftpTraceLog(' filename ',' 'REPLACE'? ')'

methods_ftptracelogoff ::= 'ftpTraceLogoff()'

methods_ftpversion ::= 'ftpVersion()'

