winobj_assocwindow ::= win '~' 'assocWindow(' handle ')'

winobj_handle ::= win '~' handle

winobj_title ::= win '~' title

winobj_title_equal ::= win '~' title '=' newtitle

winobj_wclass ::= win '~' wclass

winobj_id ::= win '~' id

winobj_coordinates ::= win '~' coordinates

winobj_state ::= win '~' state

winobj_getstyle ::= win '~' getStyle

winobj_restore ::= win '~' restore

winobj_hide ::= win '~' hide

winobj_minimize ::= win '~' minimize

winobj_maximize ::= win '~' maximize

winobj_resize ::= win '~' 'resize(' width ',' height ')'

winobj_enable ::= win '~' enable

winobj_disable ::= win '~' disable

winobj_moveto ::= win '~' 'moveTo(' x ',' y ')'

winobj_toforeground ::= win '~' toForeground

winobj_focusnextitem ::= win '~' focusNextItem

winobj_focuspreviousitem ::= win '~' focusPreviousItem

winobj_focusitem ::= win '~' 'focusItem(' wndObject ')'

winobj_findchild ::= win '~' 'findChild(' label ')'

winobj_childatposition ::= win '~' 'childAtPosition(' x ',' y ')'

winobj_next ::= win '~' next

winobj_previous ::= win '~' previous

winobj_first ::= win '~' first

winobj_last ::= win '~' last

winobj_owner ::= win '~' owner

winobj_firstchild ::= win '~' firstChild

winobj_enumeratechildren ::= win '~' enumerateChildren

winobj_sendmessage ::= win '~' 'sendMessage(' message ',' wParam ',' lParam ')'

winobj_sendcommand ::= win '~' 'sendCommand(' command ')'

winobj_sendmenucommand ::= win '~' 'sendMenuCommand(' id ')'

winobj_sendmouseclick ::= win '~' 'sendMouseClick(' ( '"RIGHT"' | '"LEFT"' | '"MIDDLE"' ) ','
                                                    ( '"UP"' | '"DOWN"' | '"DBLCLK"' ) ','
                                                    x ',' y ( ','
                                                    ( '"LEFTDOWN"' | '"RIGHTDOWN"' |
                                                      '"MIDDLEDOWN"' | '"SHIFT"' |
                                                      '"CONTROL"' ) )+ ')'

winobj_sendsyscommand ::= win '~' 'sendSysCommand(' ( '"SIZE"' | '"MOVE"' | '"MINIMIZE"' | '"MAXIMIZE"' |
                                                      '"NEXTWINDOW"' | '"PREVWINDOW"' | '"CLOSE"' |
                                                      '"VSCROLL"' | '"HSCROLL"' | '"ARRANGE"' | '"RESTORE"' |
                                                      '"TASKLIST"' | '"SCREENSAVE"' | '"CONTEXTHELP"' ) ')'

winobj_pushbutton ::= win '~' 'pushButton(' label ')'

winobj_sendkey ::= win '~' 'sendKey(' keyName ( ',' ( alt )? ( ',' ext )? )? ')'

winobj_sendchar ::= win '~' 'sendChar(' character ( ',' alt )? ')'

winobj_sendkeydown ::= win '~' 'sendKeyDown(' keyName ( ',' ext )? ')'

winobj_sendkeyup ::= win '~' 'sendKeyUp(' keyName ( ',' ext )? ')'

winobj_sendtext ::= win '~' 'sendText(' text ')'

winobj_menu ::= win '~' menu

winobj_systemmenu ::= win '~' systemMenu

winobj_ismenu ::= win '~' isMenu

winobj_processmenucommand ::= win '~' 'processMenuCommand(' ( menu )? ( ',' submenu )+ ',' menuitem ')'

