menuobj_ismenu ::= mo '~' 'isMenu'

menuobj_issubmenu ::= mo '~' 'isSubMenu(' position ')'

menuobj_ischecked ::= mo '~' 'isChecked(' position ')'

menuobj_isseparator ::= mo '~' 'isSeparator(' position ')'

menuobj_items ::= mo '~' 'items'

menuobj_idOf ::= mo '~' 'idOf(' position ')'

menuobj_textof_pos ::= mo '~' 'textOf(' position ')'

menuobj_textof_id ::= mo '~' 'textOf(' id ')'

menuobj_submenu ::= mo '~' 'submenu(' position ')'

menuobj_findSubmenu ::= mo '~' 'findSubmenu(' label ')'

menuobj_findItem ::= mo '~' 'findItem(' label ')'

menuobj_processItem ::= mo '~' 'processItem(' id ')'

