svg-raildiagrams: <https://www.bottlecaps.de/rr> (2022-05-23)

oleobj_new ::= 'new(' classID ( ',' ( events )? ( ',' getObject )? )? ')'

oleobj_dispatch ::= 'dispatch(' methodname ( ( ',' arg )+ )? ')'

oleobj_getconstant ::= 'getConstant(' ( ConstantName )? ')'

oleobj_getknownevents ::= 'getKnownEvents'

oleobj_connectevents ::= 'connectEvents'

oleobj_isconnected ::= 'isConnected'

oleobj_isconnectable ::= 'isConnectable'

oleobj_disconnectevents ::= 'disconnectEvents'

oleobj_removeeventhandler ::= 'removeEventHandler'

oleobj_addeventmethod ::= 'addEventMethod(' name ',' methodObject ')'

oleobj_removeeventmethod ::= 'removeEventMethod(' name ')'

oleobj_getknownmethods ::= 'getKnownMethods'

oleobj_getobject ::= 'getObject(' moniker ',' class ')'

oleobj_getoutparameters ::= 'getOutParameters'

oleobj_unknown ::= 'unknown(' messageName ( ',' messageArgs )? ')'

olevar_new ::= 'new(' valueObject ( ',' ( varType )? ( ',' paramFlags )? )? ')'

olevar_varvalue ::= '!VARVALUE_()'

olevar_varvalue_equal ::= '!VARVALUE_' '=' newvalue

olevar_vartype ::= '!VARTYPE_()'

olevar_vartype_equal ::= '!VARTYPE_' '=' newtype

olevar_paramflags ::= '!PARAMFLAGS_()'

olevar_paramflags_equal ::= '!PARAMFLAGS_' '=' newparamflags

oleobj_class         ::= 'class'

oleobj_clsid         ::= 'CLSID'

oleobj_copy          ::= 'copy'

oleobj_hasolemethod  ::= 'hasOleMethod(' methodName ')'

oleobj_progid        ::= 'ProgID'

oleobj_start         ::= 'start( … )'

oleobj_startWith     ::= 'startWith( … )'

