methods_ftpappend ::= myftpobj '~' 'ftpAppend(' localfilename ',' remotefilename ( ',' mode )? ')'

methods_ftpchdir ::= myftpobj '~' 'ftpChDir(' newdir ')'

methods_ftpdelete ::= myftpobj '~' 'ftpDelete(' filename ')'

methods_ftpdir ::= myftpobj '~' 'ftpDir(' pattern ')'

methods_ftpget ::= myftpobj '~' 'ftpGet(' localfilename ',' remotefilename ( ',' mode )? ')'

methods_ftpgetmode ::= myftpobj '~' 'ftpGetMode()'

methods_ftpgettype ::= myftpobj '~' 'ftpGetType()'

methods_ftplogoff ::= myftpobj '~' 'ftpLogoff()'

methods_ftpls ::= myftpobj '~' 'ftpLs(' pattern ')'

methods_ftpmkdir ::= myftpobj '~' 'ftpMkDir(' newdir ')'

methods_ftpput ::= myftpobj '~' 'ftpPut(' localfilename ',' remotefilename ( ',' mode )? ')'

methods_ftpputunique ::= myftpobj '~' 'ftpPutUnique(' localfilename ',' remotefilename ( ',' mode )? ')'

methods_ftppwd ::= myftpobj '~' 'ftpPwd()'

methods_ftpquote ::= myftpobj '~' 'ftpQuote(' cmd ')'

methods_ftprename ::= myftpobj '~' 'ftpRename(' oldfile ',' newfile ')'

methods_ftprmdir ::= myftpobj '~' 'ftpRmDir(' newdir ')'

methods_ftpsetmode ::= myftpobj '~' 'ftpSetMode(' ( '"PASSIVE"' | '"ACTIVE"') ')'

methods_ftpsettype ::= myftpobj '~' 'ftpSetType(' ( '"ASCII"' | '"BINARY"') ')'

methods_ftpsetuser ::= myftpobj '~' 'ftpSetUser(' host ',' user
                                                  ( ',' ( password )? ( ',' acct )? )? ')'

methods_ftpsite ::= myftpobj '~' 'ftpSite(' cmd ')'

methods_ftpsys ::= myftpobj '~' 'ftpSys()'

methods_ftptrace ::= myftpobj '~' 'ftpTrace()'

methods_ftptracelog ::= myftpobj '~' 'ftpTraceLog(' filename ( '"REPLACE"' )? ')'

methods_ftptracelogoff ::= myftpobj '~' 'ftpTraceLogoff()'

methods_ftpversion ::= myftpobj '~' 'ftpVersion()'

