winreg_new ::= 'new' 

winreg_classes_root ::= 'classes_root' 

winreg_close ::= 'close(' ( key_handle )? ')'

winreg_connect ::= 'connect(' key ',' computer ')'

winreg_create ::= 'create(' ( parent )? ',' subkey ')'

winreg_current_key ::= 'current_key()'

winreg_current_key_equal ::= 'current_key' '='

winreg_current_user ::= 'current_user' 

winreg_delete ::= 'delete(' ( keyHandle )? ',' subkeyName ')'

winreg_deletekey ::= 'deleteKey(' ( keyHandle )? ',' subkeyName ')'

winreg_deletevalue ::= 'deleteValue(' ( key_handle )? ( ',' value )? ')'

winreg_flush ::= 'flush(' ( key_handle )? ')'

winreg_getvalue ::= 'getValue(' ( key_handle )? ( ',' value )? ')'

winreg_list ::= 'list(' ( key_handle )? ',' 'stem.' ')'

winreg_listvalues ::= 'listValues(' ( key_handle )? ',' 'variable.' ')'

winreg_load ::= 'load(' ( key_handle )? ',' subkeyname ',' filename ')'

winreg_local_machine ::= 'local_machine' 

winreg_open ::= 'open(' ( parentHandle ( ',' ( subkey )? ( ',' access )? )? )? ')'

winreg_query ::= 'query(' ( key_handle )? ')'

winreg_replace ::= 'replace(' ( key_handle )? ',' ( subkeyname )? ',' newfilename ',' oldfilename ')'

winreg_restore ::= 'restore(' ( key_handle )? ',' filename ( ',' ( 'VOLATILE' )? )? ')'

winreg_save ::= 'save(' ( key_handle )? ',' filename ')'

winreg_setvalue ::= 'setValue(' ( key_handle )? ',' ( name )? ',' value 
                                ( ',' ( 'NORMAL' | 'EXPAND' | 'MULTI' | 'NUMBER' | 'BINARY' | 'NONE' ) )? ')'

winreg_unload ::= 'unload(' ( key_handle )? ',' subkey ')'

winreg_users ::= 'users' 

