winmgr_desktopwindow ::= wmgr '~' 'desktopWindow'

winmgr_find ::= wmgr '~' 'find(' title ')'

winmgr_foregroundwindow ::= wmgr '~' 'foregroundWindow'

winmgr_windowatposition ::= wmgr '~' 'windowAtPosition(' x ',' y ')'

winmgr_consoletitle ::= wmgr '~' 'consoleTitle'

winmgr_consoletitle_equal ::= wmgr '~' consoleTitle '=' title

winmgr_sendtexttowindow ::= wmgr '~' 'sendTextToWindow(' title ',' text ')'

winmgr_pushbuttoninwindow ::= wmgr '~' 'pushButtonInwindow(' title ',' text ')'

winmgr_processmenucommand ::= wmgr '~' 'processMenuCommand(' ( title )? ',' ( popup )?
                                                             ( ',' ( submenu )? )+ ',' menuItem ')'

winmgr_broadcastsettingchanged ::= wmgr '~' 'broadcastSettingChanged' ( '(' timeout ')' )?

