winmgr_desktopwindow ::= 'desktopWindow'

winmgr_find ::= 'find(' title ')'

winmgr_foregroundwindow ::= 'foregroundWindow'

winmgr_windowatposition ::= 'windowAtPosition(' x ',' y ')'

winmgr_consoletitle ::= 'consoleTitle'

winmgr_consoletitle_equal ::= 'consoleTitle' '=' title

winmgr_sendtexttowindow ::= 'sendTextToWindow(' title ',' text ')'

winmgr_pushbuttoninwindow ::= 'pushButtonInwindow(' title ',' text ')'

winmgr_processmenucommand ::= 'processMenuCommand(' ( title )? ',' ( popup )?
                                                             ( ',' ( submenu )? )+ ',' menuItem ')'

winmgr_broadcastsettingchanged ::= 'broadcastSettingChanged' ( '(' timeOut ')' )?

