/*----------------------------------------------------------------------------*/
/*                                                                            */
/* Copyright (c) 2008 Rexx Language Association. All rights reserved.         */
/*                                                                            */
/* This program and the accompanying materials are made available under       */
/* the terms of the Common Public License v1.0 which accompanies this         */
/* distribution. A copy is also available at the following address:           */
/* http://www.oorexx.org/license.html                                         */
/*                                                                            */
/* Redistribution and use in source and binary forms, with or                 */
/* without modification, are permitted provided that the following            */
/* conditions are met:                                                        */
/*                                                                            */
/* Redistributions of source code must retain the above copyright             */
/* notice, this list of conditions and the following disclaimer.              */
/* Redistributions in binary form must reproduce the above copyright          */
/* notice, this list of conditions and the following disclaimer in            */
/* the documentation and/or other materials provided with the distribution.   */
/*                                                                            */
/* Neither the name of Rexx Language Association nor the names                */
/* of its contributors may be used to endorse or promote products             */
/* derived from this software without specific prior written permission.      */
/*                                                                            */
/* THIS SOFTWARE IS PROVIDED BY THE COPYright HOLDERS AND CONTRIBUTORS        */
/* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT          */
/* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS          */
/* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYright   */
/* OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,      */
/* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED   */
/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,        */
/* OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY     */
/* OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING    */
/* NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS         */
/* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.               */
/*                                                                            */
/*----------------------------------------------------------------------------*/


-- These are the real external functions we are testing
::routine tstargs000 EXTERNAL "LIBRARY orxfunction TstArgs000"
::routine tstargs001 EXTERNAL "LIBRARY orxfunction TstArgs001"
::routine tstargs002 EXTERNAL "LIBRARY orxfunction TstArgs002"
::routine tstargs003 EXTERNAL "LIBRARY orxfunction TstArgs003"
::routine tstargs004 EXTERNAL "LIBRARY orxfunction TstArgs004"
::routine tstargs005 EXTERNAL "LIBRARY orxfunction TstArgs005"
::routine tstargs006 EXTERNAL "LIBRARY orxfunction TstArgs006"
::routine tstargs007 EXTERNAL "LIBRARY orxfunction TstArgs007"
::routine tstargs008 EXTERNAL "LIBRARY orxfunction TstArgs008"
::routine tstargs009 EXTERNAL "LIBRARY orxfunction TstArgs009"
::routine tstargs010 EXTERNAL "LIBRARY orxfunction TstArgs010"
::routine tstargs011 EXTERNAL "LIBRARY orxfunction TstArgs011"
::routine tstargs012 EXTERNAL "LIBRARY orxfunction TstArgs012"
::routine tstargs013 EXTERNAL "LIBRARY orxfunction TstArgs013"
::routine tstargs014 EXTERNAL "LIBRARY orxfunction TstArgs014"
::routine tstargs015 EXTERNAL "LIBRARY orxfunction TstArgs015"
::routine tstargs016 EXTERNAL "LIBRARY orxfunction TstArgs016"
::routine tstargs017 EXTERNAL "LIBRARY orxfunction TstArgs017"
::routine tstargs018 EXTERNAL "LIBRARY orxfunction TstArgs018"
::routine tstargs019 EXTERNAL "LIBRARY orxfunction TstArgs019"
::routine tstargs020 EXTERNAL "LIBRARY orxfunction TstArgs020"
::routine tstargs021 EXTERNAL "LIBRARY orxfunction TstArgs021"
::routine tstargs022 EXTERNAL "LIBRARY orxfunction TstArgs022"
::routine tstargs023 EXTERNAL "LIBRARY orxfunction TstArgs023"
::routine tstargs024 EXTERNAL "LIBRARY orxfunction TstArgs024"
::routine tstargs025a EXTERNAL "LIBRARY orxfunction TstArgs025a"
::routine tstargs025b EXTERNAL "LIBRARY orxfunction TstArgs025b"
::routine tstargs025c EXTERNAL "LIBRARY orxfunction TstArgs025c"

