address ::= ADDRESS ( environment expression | VALUE expression )? ';'

arg ::= ARG ( template_list )? ';'

parse_upper_arg ::= PARSE UPPER ARG ( template_list )? ';'

call ::= CALL (name | '(' expr ')' )? ( expression ( ( ',' expression )+ )? )? |
              OFF ( ANY | ERROR | FAILURE | HALT | NOTREADY | USER ( usercondition ) ) |
              ON ( ANY | ERROR | FAILURE | HALT | NOTREADY | USER ( usercondition )? ) 
                 ( name trapname )? ';'

funct_call ::= result '=' 'name(' expression ( ( ',' expression)+ )? ')' ';'

do ::= DO ( LABEL name )? ( repetitor )? ( conditional )? ';' 
          instruction ';' ( ( instruction ';' )+ )? END ( name )? ';'

do_forever ::= ( control2 '=' expri ( TO exprt )? ( BY exprb )? ( FOR rxprf )? |
               control2 OVER collection |
               FOREVER |
               exprr )

do_while ::= ( WHILE exprw | UNTIL expru )

drop ::= DROP ( ( ( name | '(' name ')' ) )+ )? ';'

exit ::= EXIT ( expression )? ';'

expose ::= EXPOSE ( ( ( name | '(' name ')' ) )+ )? ';'

forward ::= FORWARD ( CONTINUE )? ( ARGUMENTS expra | ARRAY expri ( ( ',' expri )+ )? )
            ( MESSAGE exprm )? ( CLASS exprs )? ( TO exprt )? ';'

guard ::= GUARD ( ON ( WHEN expression )? |
                  OFF ( WHEN expression )? ) ';'

if ::= IF expression ( ';' )? THEN ( ';' )? instruction ( ELSE ( ';' )? instruction )?

interpret ::= INTERPRET expression ';'

iterate ::= ITERATE ( name )? ';'

leave ::= LEAVE ( name )? ';'

loop ::= LOOP ( LABEL name )? ( repetitor )? ( conditional )? ';' 
          instruction ';' ( ( instruction ';' )+ )? END ( name )? ';'

nop ::= NOP ';'

numeric ::= NUMERIC ( DIGITS ( expression )? |
                      FORM ( SCIENTIFIC | ENGINEERING | ( VALUE )? expression2 )? |
                      FUZZ ( expression )? ) ';'

options ::= OPTIONS ( expression )? ';'

parse ::= PARSE ( UPPER | LOWER )? ( CASELESS )? ( ARG | LINEIN | PULL | SOURCE |
                VALUE ( expression )? WITH | VAR name | VERSION ) ( template_list )? ';'

parse_val ::= PARSE VALUE LINEIN '()' WITH ( template_list )? ';'

proc ::= PROCEDURE ( EXPOSE ( name | '(' name ')' )+ )? ';'

pull ::= PULL ( template_list )? ';'

parse_upper_pull ::= PARSE UPPER PULL ( template_list )? ';'

push ::= PUSH (expression )? ';'

queue ::= QUEUE (expression )? ';'

raise ::= RAISR ( condition | ERROR errorcode | FAILURE failurecode | SYNTAX number |
                  USER usercondition | PRPOAGATE ) ( options )? ';'

raise_options ::= ( ADDITIONAL expra | ARRAY expri ( ( ',' expri )+ )? )? ( DESCRIPTION exprd )?
                  ( EXIT ( expre )?| RETURN ( exprr )? )?

reply ::= REPLY (expression )? ';'

retrun ::= RETURN (expression )? ';'

say ::= SAY (expression )? ';'

call_linout ::= CALL LINEOUT ',' ( expression )? ';'

select ::= SELECT ( LABEL name )? ( WHEN expression ( ';' )? THEN ( ';' )? instruction ';' )+
                  ( OTHERWISE ( ';' )? ( ( instruction ';' )+ )? )? END ( name )? ';'

signal ::= SIGNAL ( labelname |
                    ( VALUE )? expression |
                    OFF ( ANY | ERROR | FAILURE | HALT | LOSTDOGITS | NOMETHOD |
                          NOSTRING | NOTREADY | NOVALUE | SYNTAX | USER usercondition ) |
                    ON ( ANY | ERROR | FAILURE | HALT | LOSTDOGITS | NOMETHOD |
                         NOSTRING | NOTREADY | NOVALUE | SYNTAX | USER usercondition ) 
                       ( NAME trapname )? ) ';'

trace1 ::= TRACE ( number |
                   ( '?' )+ ( 'Normal' | 'All' | 'Commands' | 'Error' | 'Failure' |
                              'Intermediates' | 'Labels' | 'Off' | ''Results' )? ';'

trace2 ::= TRACE ( string | symbol | ( VALUE )? expression )? ';'

use ::= USE ( STRICT )? ARG ( ( name '=' expression )+ )? ';'
