menuobj_ismenu ::= 'isMenu'

menuobj_issubmenu ::= 'isSubMenu(' position ')'

menuobj_ischecked ::= 'isChecked(' position ')'

menuobj_isseparator ::= 'isSeparator(' position ')'

menuobj_items ::= 'items'

menuobj_idof ::= 'idOf(' position ')'

menuobj_textof_pos ::= 'textOf(' position ')'

menuobj_textof_id ::= 'textOf(' id ')'

menuobj_submenu ::= 'submenu(' position ')'

menuobj_findsubmenu ::= 'findSubmenu(' label ')'

menuobj_finditem ::= 'findItem(' label ')'

menuobj_processitem ::= 'processItem(' id ')'

