mime_new ::= 'new(' ( type )? ')'

mime_addcontent ::= 'addContent(' string ')'

mime_content ::= 'content()'

mime_description ::= 'description(' ( newdescription )? ')'

mime_disposition ::= 'disposition(' ( newdisposition )? ')'

mime_encoding ::= 'encoding(' ( newencoding )? ')'

mime_id ::= 'id(' ( newid )? ')'

mime_string ::= 'string()'

mime_type ::= 'type(' ( newtype )? ')'

mimemulti_new ::= 'new(' ( type )? ')'

mimemulti_addpart ::= 'addPart(' part ')'

mimemulti_description ::= 'description(' ( newdescription )? ')'

mimemulti_disposition ::= 'disposition(' ( newdisposition )? ')'

mimemulti_encoding ::= 'encoding(' ( newencoding )? ')'

mimemulti_id ::= 'id(' ( newid )? ')'

mimemulti_string ::= 'string()'

mimemulti_type ::= 'type(' ( newtype )? ')'

