smtp_new ::= 'new()'

smtp_authid ::= 'authid(' ( newauthid )? ')'

smtp_cmdresponse ::= 'cmdresponse()'

smtp_connect ::= 'connect(' smthhost ( ',' authid ( ',' password )? )? ')'

smtp_debug ::= 'debug(' ( flag )? ')'

smtp_localhost ::= 'localhost()'

smtp_logoff ::= 'logoff()'

smtp_password ::= 'password(' ( newpassword )? ')'

smtp_response ::= 'response()'

smtp_send ::= 'send(' msg ')'

smtp_smtperrno ::= 'smtherrno()'

smtpmsg_new ::= 'new()'

smtpmsg_addrecipient ::= 'addRecipient(' recp ')'

smtpmsg_content ::= 'content(' ( part )? ')'

smtpmsg_from ::= 'from(' ( fromaddress )? ')'

smtpmsg_recipients ::= 'recipients()'

smtpmsg_subject ::= 'subject(' ( newsubject )? ')'

