socket_gethostbyaddr ::= 'getHostByAddr(' ipaddr ')'

socket_gethostbyname ::= 'getHostByName(' hostname ')'

socket_gethostid ::= 'getHostId()'

socket_accept ::= 'accept()'

socket_bind ::= 'bind(' address ')'

socket_close ::= 'close()'

socket_connect ::= 'connect(' address ')'

socket_getoption ::= 'getOption(' option ')'

socket_getpeername ::= 'getPeerName()'

socket_getsockname ::= 'getSockName()'

socket_new ::= 'new(' ( domain ( ',' type ( ',' protocol )? )? )? ')'

socket_ioctl ::= 'ioctl(' cmd ',' data ')'

socket_listen ::= 'listen(' backlog ')'

socket_recv ::= 'recv(' length ')'

socket_recvfrom ::= 'recvFrom(' length ',' address ')'

socket_select ::= 'select(' reads ',' writes ',' excepts ',' timeout ')'

socket_send ::= 'send(' data ')'

socket_setoption ::= 'setOption(' name ',' value ')'

socket_string ::= 'string()'

inetaddr_address ::= 'address()'

inetaddr_address_equal ::= 'address(' ipaddress ')'

inetaddr_family ::= 'family()'

inetaddr_family_equal ::= 'family(' newfamily ')'

inetaddr_init ::= 'init(' hostname ',' port ( ',' family )? ')'

inetaddr_makestem ::= 'makestem()'

inetaddr_port ::= 'port()'

inetaddr_port_equal ::= 'port(' newport ')'

hostinfo_addr ::= 'addr()'

hostinfo_address ::= 'address()'

hostinfo_alias ::= 'alias()'

hostinfo_name ::= 'name()'

hostinfo_init ::= 'init(' hostname ')'

hostinfo_makestem ::= 'makestem()'

