streamsock_new ::= 'new(' host ',' port ( ',' bufsize )? ')'

streamsock_charin ::= 'charIn' ( '(' string ( ',' length )? ')' )?

streamsock_charout ::= 'charOut' ( '(' string ( ',' start )? ')' )?

streamsock_chars ::= 'chars()'

streamsock_close ::= 'close()'

streamsock_description ::= 'description()'

streamsock_linein ::= 'lineIn' ( '(' line ( ',' count )? ')' )?

streamsock_lineout ::= 'lineOut' ( '(' string ( ',' line )? ')' )?

streamsock_lines ::= 'lines()'

streamsock_open ::= 'open()'

streamsock_position ::= 'position()'

streamsock_say ::= 'say' ( '(' string ')' )?

streamsock_state ::= 'state()'

streamsock_string ::= 'string()'

