

/*----------------------------------------------------------------------------*/
/*                                                                            */
/* Copyright (c) 1995, 2004 IBM Corporation. All rights reserved.             */
/* Copyright (c) 2005-2018 Rexx Language Association. All rights reserved.    */
/*                                                                            */
/* This program and the accompanying materials are made available under       */
/* the terms of the Common Public License v1.0 which accompanies this         */
/* distribution. A copy is also available at the following address:           */
/* https://www.oorexx.org/license.html                                        */
/*                                                                            */
/* Redistribution and use in source and binary forms, with or                 */
/* without modification, are permitted provided that the following            */
/* conditions are met:                                                        */
/*                                                                            */
/* Redistributions of source code must retain the above copyright             */
/* notice, this list of conditions and the following disclaimer.              */
/* Redistributions in binary form must reproduce the above copyright          */
/* notice, this list of conditions and the following disclaimer in            */
/* the documentation and/or other materials provided with the distribution.   */
/*                                                                            */
/* Neither the name of Rexx Language Association nor the names                */
/* of its contributors may be used to endorse or promote products             */
/* derived from this software without specific prior written permission.      */
/*                                                                            */
/* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS        */
/* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT          */
/* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS          */
/* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT   */
/* OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,      */
/* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED   */
/* TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,        */
/* OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY     */
/* OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING    */
/* NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS         */
/* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.               */
/*                                                                            */
/*----------------------------------------------------------------------------*/
/******************************************************************************/
/* REXX  Support                                                              */
/*                                                                            */
/* Rexx primitive class id codes                                              */
/*                                                                            */
/*        -- DO NOT CHANGE THIS FILE, ALL CHANGES WILL BE LOST! --            */
/*                  -- FILE WAS GENERATED BY ClassTypeIds.xsl --              */
/******************************************************************************/

#ifndef ClassTypeCodes_Included
#define ClassTypeCodes_Included

typedef enum
{
    T_First_Primitive_Class = 0,
    T_First_Exported_Class = 0,

    T_Object = 0,
    T_ObjectClass = 1,
    T_Class = 2,
    T_ClassClass = 3,
    T_Array = 4,
    T_ArrayClass = 5,
    T_Directory = 6,
    T_DirectoryClass = 7,
    T_Integer = 8,
    T_IntegerClass = 9,
    T_List = 10,
    T_ListClass = 11,
    T_Message = 12,
    T_MessageClass = 13,
    T_Method = 14,
    T_MethodClass = 15,
    T_NumberString = 16,
    T_NumberStringClass = 17,
    T_Queue = 18,
    T_QueueClass = 19,
    T_Stem = 20,
    T_StemClass = 21,
    T_String = 22,
    T_StringClass = 23,
    T_Supplier = 24,
    T_SupplierClass = 25,
    T_Table = 26,
    T_TableClass = 27,
    T_StringTable = 28,
    T_StringTableClass = 29,
    T_Relation = 30,
    T_RelationClass = 31,
    T_MutableBuffer = 32,
    T_MutableBufferClass = 33,
    T_Pointer = 34,
    T_PointerClass = 35,
    T_Buffer = 36,
    T_BufferClass = 37,
    T_WeakReference = 38,
    T_WeakReferenceClass = 39,
    T_Routine = 40,
    T_RoutineClass = 41,
    T_Package = 42,
    T_PackageClass = 43,
    T_RexxContext = 44,
    T_RexxContextClass = 45,
    T_IdentityTable = 46,
    T_IdentityTableClass = 47,
    T_StackFrame = 48,
    T_StackFrameClass = 49,
    T_Set = 50,
    T_SetClass = 51,
    T_Bag = 52,
    T_BagClass = 53,
    T_RexxInfo = 54,
    T_RexxInfoClass = 55,
    T_VariableReference = 56,
    T_VariableReferenceClass = 57,
    T_EventSemaphore = 58,
    T_EventSemaphoreClass = 59,
    T_MutexSemaphore = 60,
    T_MutexSemaphoreClass = 61,
    T_RexxUnicodeServices = 62,
    T_RexxUnicodeServicesClass = 63,

    T_Last_Exported_Class = 63,
    
    T_First_Internal_Class = 64,

    T_NilObject = 64,
    T_Behaviour = 65,
    T_MethodDictionary = 66,
    T_LibraryPackage = 67,
    T_RexxCode = 68,
    T_NativeMethod = 69,
    T_NativeRoutine = 70,
    T_RegisteredRoutine = 71,
    T_CPPCode = 72,
    T_AttributeGetterCode = 73,
    T_AttributeSetterCode = 74,
    T_ConstantGetterCode = 75,
    T_AbstractCode = 76,
    T_DelegateCode = 77,
    T_SmartBuffer = 78,
    T_IdentityHashContents = 79,
    T_EqualityHashContents = 80,
    T_MultiValueContents = 81,
    T_StringHashContents = 82,
    T_ListContents = 83,
    T_Variable = 84,
    T_VariableDictionary = 85,
    T_VariableTerm = 86,
    T_CompoundVariableTerm = 87,
    T_StemVariableTerm = 88,
    T_DotVariableTerm = 89,
    T_IndirectVariableTerm = 90,
    T_FunctionCallTerm = 91,
    T_MessageSendTerm = 92,
    T_UnaryOperatorTerm = 93,
    T_BinaryOperatorTerm = 94,
    T_LogicalTerm = 95,
    T_ListTerm = 96,
    T_Instruction = 97,
    T_AddressInstruction = 98,
    T_AssignmentInstruction = 99,
    T_CallInstruction = 100,
    T_DynamicCallInstruction = 101,
    T_QualifiedCallInstruction = 102,
    T_CallOnInstruction = 103,
    T_CommandInstruction = 104,
    T_SimpleDoInstruction = 105,
    T_DoForeverInstruction = 106,
    T_DoOverInstruction = 107,
    T_DoOverUntilInstruction = 108,
    T_DoOverWhileInstruction = 109,
    T_DoOverForInstruction = 110,
    T_DoOverForUntilInstruction = 111,
    T_DoOverForWhileInstruction = 112,
    T_ControlledDoInstruction = 113,
    T_ControlledDoUntilInstruction = 114,
    T_ControlledDoWhileInstruction = 115,
    T_DoWhileInstruction = 116,
    T_DoUntilInstruction = 117,
    T_DoCountInstruction = 118,
    T_DoCountUntilInstruction = 119,
    T_DoCountWhileInstruction = 120,
    T_DropInstruction = 121,
    T_ElseInstruction = 122,
    T_EndInstruction = 123,
    T_EndIfInstruction = 124,
    T_ExitInstruction = 125,
    T_ExposeInstruction = 126,
    T_ForwardInstruction = 127,
    T_GuardInstruction = 128,
    T_IfInstruction = 129,
    T_CaseWhenInstruction = 130,
    T_InterpretInstruction = 131,
    T_LabelInstruction = 132,
    T_LeaveInstruction = 133,
    T_MessageInstruction = 134,
    T_NopInstruction = 135,
    T_NumericInstruction = 136,
    T_OptionsInstruction = 137,
    T_OtherwiseInstruction = 138,
    T_ParseInstruction = 139,
    T_ProcedureInstruction = 140,
    T_QueueInstruction = 141,
    T_RaiseInstruction = 142,
    T_ReplyInstruction = 143,
    T_ReturnInstruction = 144,
    T_SayInstruction = 145,
    T_SelectInstruction = 146,
    T_SelectCaseInstruction = 147,
    T_SignalInstruction = 148,
    T_DynamicSignalInstruction = 149,
    T_SignalOnInstruction = 150,
    T_ThenInstruction = 151,
    T_TraceInstruction = 152,
    T_UseInstruction = 153,
    T_UseLocalInstruction = 154,
    T_DoWithInstruction = 155,
    T_DoWithUntilInstruction = 156,
    T_DoWithWhileInstruction = 157,
    T_DoWithForInstruction = 158,
    T_DoWithForUntilInstruction = 159,
    T_DoWithForWhileInstruction = 160,
    T_ClassDirective = 161,
    T_LibraryDirective = 162,
    T_RequiresDirective = 163,
    T_CompoundElement = 164,
    T_ParseTrigger = 165,
    T_ProgramSource = 166,
    T_ArrayProgramSource = 167,
    T_BufferProgramSource = 168,
    T_FileProgramSource = 169,
    T_NumberArray = 170,
    T_ClassResolver = 171,
    T_QualifiedFunction = 172,
    T_PointerBucket = 173,
    T_PointerTable = 174,
    T_SpecialDotVariableTerm = 175,
    T_VariableReferenceOp = 176,
    T_UseArgVariableRef = 177,
    T_CommandIOConfiguration = 178,
    T_AddressWithInstruction = 179,
    T_ConstantDirective = 180,

    T_Last_Internal_Class = 180,
    
    T_First_Transient_Class = 181,

    T_Memory = 181,
    T_InternalStack = 182,
    T_PushThroughStack = 183,
    T_Activity = 184,
    T_Activation = 185,
    T_NativeActivation = 186,
    T_ActivationFrameBuffer = 187,
    T_Envelope = 188,
    T_LanguageParser = 189,
    T_Clause = 190,
    T_Token = 191,
    T_DoBlock = 192,
    T_InterpreterInstance = 193,
    T_SecurityManager = 194,
    T_CommandHandler = 195,
    T_MapBucket = 196,
    T_MapTable = 197,
    T_TrapHandler = 198,
    T_CommandIOContext = 199,
    T_StemOutputTarget = 200,
    T_StreamObjectOutputTarget = 201,
    T_StreamOutputTarget = 202,
    T_CollectionOutputTarget = 203,
    T_BufferingOutputTarget = 204,
    T_StemInputSource = 205,
    T_StreamObjectInputSource = 206,
    T_StreamInputSource = 207,
    T_ArrayInputSource = 208,
    T_RexxQueueOutputTarget = 209,

    T_Last_Transient_Class = 209,
    T_Last_Primitive_Class = 209,
    T_Last_Class_Type = 209,
    
} ClassTypeCode;

/* -------------------------------------------------------------------------- */
/* --            ==================================================        -- */
/* --            DO NOT CHANGE THIS FILE, ALL CHANGES WILL BE LOST!        -- */
/* --            ==================================================        -- */
/* -------------------------------------------------------------------------- */
#endif

