funcs_sockloadfuncs ::= 'SockLoadFuncs(' ( parm )? ')'

funcs_sockversion ::= 'SockVersion()'

funcs_sockaccept ::= 'SockAccept(' socket ( ',' address )? ')'

funcs_sockbind ::= 'SockBind(' socket ',' address ')'

funcs_sockclose ::= 'SockClose(' socket ')'

funcs_sockconnect ::= 'SockConnect(' socket ',' address ')'

funcs_sockgethostbyaddr ::= 'SockGetHostByAddr(' dotAddress ',' host ( ',' domain )? ')'

funcs_sockgethostbyname ::= 'SockGetHostByName(' nameAddress ',' host ')'

funcs_sockgethostid ::= 'SockGetHostId()'

funcs_sockgetpeername ::= 'SockGetPeerName(' socket ',' address ')'

funcs_sockgetsockname ::= 'SockGetSockName(' socket ',' address ')'

funcs_sockgetsockopt ::= 'SockGetSockOpt(' socket ',' level ',' optName ',' optVal ')'

funcs_sockinit ::= 'SockInit()'

funcs_sockioctl ::= 'SockIoctl(' socket ',' ioctlCmd ',' ioctlData ')'

funcs_socklisten ::= 'SockListen(' socket ',' backlog ')'

funcs_sockpsock_errno ::= 'SockPSock_Errno(' ( error_string )? ')'

funcs_sockrecv ::= 'SockRecv(' socket ',' var ',' len ( ',' flags )? ')'

funcs_sockrecvfrom ::= 'SockRecvFrom(' socket ',' var ',' len ( ',' flags )? ',' address ')'

funcs_sockselect ::= 'SockSelect(' reads ',' writes ',' excepts ( ',' timeout )? ')'

funcs_socksend ::= 'SockSend(' socket ',' data ( ',' flags )? ')'

funcs_socksendto ::= 'SockSendTo(' socket ',' data ( ',' flags )? ',' address ')'

funcs_socksetsockopt ::= 'SockSetSockOpt(' socket ',' level ',' optName ',' optVal ')'

funcs_sockshutdown ::= 'SockShutDown(' socket ',' howto ')'

funcs_socksock_errno ::= 'SockSock_Errno()'

funcs_socksocket ::= 'SockSocket(' domain ',' type ',' protocol ')'

funcs_socksoclose ::= 'SockSoClose(' socket ')'

