winevent_new ::= 'new'

winevent_minimumreadmin ::= 'minimumReadMin'

winevent_minimumreadmax ::= 'minimumReadMax'

winevent_minimumreadbuffer ::= 'minimumReadBuffer'

winevent_events ::= 'events'

winevent_open ::= 'open(' server? ',' source? ')'

winevent_close ::= 'close'

winevent_readrecords ::= 'readRecords(' direction? ',' server? ',' source? ',' start? ',' count? ')'

winevent_write ::= 'write(' srvr ',' src? ',' type? ',' category? ',' id? ',' data? ',' string* ')'

winevent_clear ::= 'clear(' srvr? ',' src? ',' type? ',' backupFileName? ')'

winevent_minimumread ::= 'minimumRead'

winevent_minimumread_equal ::= 'minimumRead' '=' sizeKB

winevent_isfull ::= 'isFull(' server? ',' source? ')'

winevent_getnumber ::= 'getNumber(' server? ',' source? ')'

winevent_getlognames ::= 'getLogNames(' names ')'

winevent_getlast ::= 'getLast(' server? ',' source? ')'

winevent_getfirst ::= 'getFirst(' server? ',' source? ')'

