streamsocket_new ::= 'new(' host ',' port ( ',' bufsize )? ')'

streamsocket_charin ::= 'charIn(' start? ',' length? ')'

streamsocket_charout ::= 'charOut(' string (',' start)? ')'

streamsocket_chars ::= 'chars()'

streamsocket_close ::= 'close()'

streamsocket_description ::= 'description()'

streamsocket_linein ::= 'lineIn(' line (',' count)? ')'

streamsocket_lineout ::= 'lineOut(' string (',' line )? ')'

streamsocket_lines ::= 'lines()'

streamsocket_open ::= 'open()'

streamsocket_position ::= 'position()'

streamsocket_say ::= 'say(' string ')'

streamsocket_state ::= 'state()'

streamsocket_string ::= 'string()'

