clipboard_copy ::= 'copy(' text ',' codepage? ',' translateflags? ')'

clipboard_makearray ::= 'makearray'

clipboard_paste ::= 'paste(' codepage? ',' mappingflags? ',' defaultchar? ')'

clipboard_empty ::= 'empty'

clipboard_isdataavailable ::= 'isDataAvailable'

clipboard_locale ::= 'locale'
