clipboard_copy ::= cb '~' 'copy(' text ')'

clipboard_makearray ::= cb '~' 'makearray'

clipboard_paste ::= cb '~' 'paste'

clipboard_empty ::= cb '~' 'empty'

clipboard_isdataavailable ::= cb '~' 'isDataAvailable'

